// Generated by `june db types`. Do not edit — re-run after a migration.
import "@junejs/juno";

declare module "@junejs/juno" {
  interface Schema {
    users: {
      id: number;
      name: string;
    };
  }
}
