// AUTO-GENERATED by `june build` — edit content/**/*.md, not this file.
export type ContentEntry = { slug: string; data: Record<string, string | string[]>; body: string; original: string; html: string };
export const POSTS: ContentEntry[] = [
  {
    "slug": "hello",
    "data": {
      "title": "Hello, June",
      "date": "2026-06-11",
      "description": "The first post in the June Basic fixture.",
      "tags": [
        "june",
        "rsc",
        "agents"
      ]
    },
    "body": "# Hello, June\n\nThis markdown file is served three ways:\n\n- **as HTML** in the `view` projection (rendered with `marked`),\n- **as JSON** frontmatter + body via `.json`,\n- **verbatim** as the `.md` projection — exactly these bytes, frontmatter and all.\n\nThat last one is the differentiator: an agent fetching `/posts/hello.md` reads\nthe authored source, not a lossy reconstruction.\n",
    "original": "---\ntitle: Hello, June\ndate: 2026-06-11\ndescription: The first post in the June Basic fixture.\ntags: [june, rsc, agents]\n---\n\n# Hello, June\n\nThis markdown file is served three ways:\n\n- **as HTML** in the `view` projection (rendered with `marked`),\n- **as JSON** frontmatter + body via `.json`,\n- **verbatim** as the `.md` projection — exactly these bytes, frontmatter and all.\n\nThat last one is the differentiator: an agent fetching `/posts/hello.md` reads\nthe authored source, not a lossy reconstruction.\n",
    "html": "<h1>Hello, June</h1>\n<p>This markdown file is served three ways:</p>\n<ul>\n<li><strong>as HTML</strong> in the <code>view</code> projection (rendered with <code>marked</code>),</li>\n<li><strong>as JSON</strong> frontmatter + body via <code>.json</code>,</li>\n<li><strong>verbatim</strong> as the <code>.md</code> projection — exactly these bytes, frontmatter and all.</li>\n</ul>\n<p>That last one is the differentiator: an agent fetching <code>/posts/hello.md</code> reads\nthe authored source, not a lossy reconstruction.</p>\n"
  }
];
export const post = (slug: string): ContentEntry | null => POSTS.find((p) => p.slug === slug) ?? null;
