// AUTO-GENERATED by June — do not edit. Lazy loaders for client:* islands.
// Maps each island name to a loader that resolves its component; hydrateIslands uses it.
export const ISLAND_LOADERS: Record<string, () => Promise<unknown>> = {
  "AddToCart": () => import("./cart/AddToCart").then((m) => m.AddToCart),
  "CartBadge": () => import("./cart/CartBadge").then((m) => m.CartBadge),
  "Counter": () => import("./counter/Counter").then((m) => m.Counter),
  "Panel": () => import("./slot/Panel").then((m) => m.Panel),
};
