// AUTO-GENERATED by June — do not edit. Compiled from this agent/ directory so
// the definition mounts without filesystem discovery (workerd has no fs).
// Regenerate with `june gen` after adding, removing, or editing agent files.
import tool_create_order from "./tools/create_order";
import channel_crisp from "./channels/crisp";
import config from "./agent";
import type { AgentModule } from "@junejs/core/agent-config";

export const agentModule: AgentModule = {
  config,
  instructions: "You are an ordering assistant. Use create_order, then confirm the order number\nin one sentence.\n",
  tools: [tool_create_order],
  skills: [],
  channels: { "crisp": channel_crisp },
  channelInstructions: {},
  connections: [],
};
export default agentModule;
