// The agent compile seam: an agent/ directory → a static _agent.gen.ts module
// that mounts where fs discovery can't run (workerd). The contract under test is
// PARITY — the compiled module, assembled through the same
// @junejs/core/agent-config entry points as native discovery, yields the same
// agent — plus the durable acceptance: skills actually mount on the DO target
// (read_skill dispatches), which fs-less workers never had.

import { afterEach, beforeEach, describe, expect, test } from "bun:test";
import { mkdirSync, mkdtempSync, readFileSync, rmSync, writeFileSync } from "node:fs";
import { tmpdir } from "node:os";
import { fileURLToPath } from "node:url";
import { dirname, join } from "node:path";

import { ACTION_REGISTRY } from "@junejs/core/agent";
import { assembleAgent, assembleDurable } from "@junejs/core/agent-config";
import { replyStream, type Model } from "@junejs/core/agent-runtime";
import { AGENT_MODULE_FILE, emitAgentModule, findAgentDir, generateAgentModule, scanAgentDir } from "../src/agent-compile";
import { discoverAgent } from "../src/agent-discover";
import { AgentDurableObject, sseTurnFinalText, type DurableStorage, type SqlStorage } from "../src/agent-durable";
import { openLocalSqliteSync } from "../src/sqlite-driver";

const FIXTURE = join(dirname(fileURLToPath(import.meta.url)), "fixtures", "agent-ops");

// Importing tools (statically via the generated module, dynamically via
// discovery) self-registers defineActions globally; isolate the registry.
let preexisting = new Map(ACTION_REGISTRY);
beforeEach(() => { preexisting = new Map(ACTION_REGISTRY); ACTION_REGISTRY.clear(); });
afterEach(() => { ACTION_REGISTRY.clear(); for (const [id, a] of preexisting) ACTION_REGISTRY.set(id, a); });

describe("scanAgentDir", () => {
  test("scans the directory into paths (code) and contents (prose)", () => {
    const scan = scanAgentDir(FIXTURE)!;
    expect(scan.name).toBe("agent-ops");
    expect(scan.hasConfig).toBe(true);
    expect(scan.instructions).toContain("operations assistant");
    expect(scan.tools).toEqual(["./tools/create_order.ts"]);
    expect(scan.skills.map((s) => s.name)).toEqual(["bulk_reorder"]);
    expect(scan.channels).toEqual(["./channels/http.ts", "./channels/slack.ts"]);
    // instructions.slack.md is a SURFACE variant (#149) — agent-level prose,
    // not a channel overlay; the legacy channels/*.md slot is empty here.
    expect(scan.surfaceVariants.map((v) => v.source)).toEqual(["slack"]);
    expect(scan.channelOverlays).toEqual([]);
    expect(scan.connections).toEqual([]);
  });

  test("skips `_`-prefixed files (the generated module itself, private helpers)", () => {
    const dir = mkdtempSync(join(tmpdir(), "june-agent-"));
    try {
      mkdirSync(join(dir, "tools"));
      writeFileSync(join(dir, "tools", "real.ts"), "export default {};");
      writeFileSync(join(dir, "tools", "_helper.ts"), "export default {};");
      writeFileSync(join(dir, AGENT_MODULE_FILE), "// generated");
      const scan = scanAgentDir(dir)!;
      expect(scan.tools).toEqual(["./tools/real.ts"]);
    } finally {
      rmSync(dir, { recursive: true, force: true });
    }
  });

  test("a directory with nothing agent-shaped scans to null", () => {
    const dir = mkdtempSync(join(tmpdir(), "june-agent-"));
    try {
      expect(scanAgentDir(dir)).toBeNull();
      expect(scanAgentDir(join(dir, "missing"))).toBeNull();
    } finally {
      rmSync(dir, { recursive: true, force: true });
    }
  });
});

describe("emitAgentModule", () => {
  test("emits static imports + inlined prose, deterministically", () => {
    const scan = scanAgentDir(FIXTURE)!;
    const code = emitAgentModule(scan);
    expect(code).toContain("AUTO-GENERATED by June");
    expect(code).toContain(`import tool_create_order from "./tools/create_order";`);
    expect(code).toContain(`import channel_http from "./channels/http";`);
    expect(code).toContain(`import config from "./agent";`);
    expect(code).toContain(`parseSkill("bulk_reorder"`);
    expect(code).toContain(`"slack":`); // the channels/slack.md overlay, inlined
    expect(code).not.toContain("node:fs"); // nothing host-bound leaks into the module
    expect(emitAgentModule(scanAgentDir(FIXTURE)!)).toBe(code);
  });

  test("tsExtensions keeps .ts specifiers (Node type-stripping consumers)", () => {
    const code = emitAgentModule(scanAgentDir(FIXTURE)!, { tsExtensions: true });
    expect(code).toContain(`import tool_create_order from "./tools/create_order.ts";`);
    expect(code).toContain(`import config from "./agent.ts";`);
  });

  test("no agent.ts → config synthesized from the directory name", () => {
    const dir = mkdtempSync(join(tmpdir(), "june-agent-"));
    try {
      const agentDir = join(dir, "support");
      mkdirSync(agentDir);
      writeFileSync(join(agentDir, "instructions.md"), "Be helpful.");
      const code = emitAgentModule(scanAgentDir(agentDir)!);
      expect(code).toContain(`const config = { name: "support" };`);
      expect(code).not.toContain("./agent.ts");
    } finally {
      rmSync(dir, { recursive: true, force: true });
    }
  });
});

describe("generateAgentModule", () => {
  test("the committed fixture module is fresh (edit fixture files ⇒ regenerate)", () => {
    const r = generateAgentModule(FIXTURE, { check: true })!;
    expect(r.stale).toBe(false);
    expect(r.written).toBe(false);
  });

  test("check mode reports stale without writing; a real run writes and settles", () => {
    const dir = mkdtempSync(join(tmpdir(), "june-agent-"));
    try {
      const agentDir = join(dir, "ops");
      mkdirSync(agentDir);
      writeFileSync(join(agentDir, "instructions.md"), "v1");
      expect(generateAgentModule(agentDir, { check: true })!.stale).toBe(true);

      expect(generateAgentModule(agentDir)!.written).toBe(true);
      expect(generateAgentModule(agentDir, { check: true })!.stale).toBe(false);
      expect(generateAgentModule(agentDir)!.written).toBe(false); // idempotent

      writeFileSync(join(agentDir, "instructions.md"), "v2"); // content edit → stale again
      expect(generateAgentModule(agentDir, { check: true })!.stale).toBe(true);
      expect(readFileSync(join(agentDir, AGENT_MODULE_FILE), "utf8")).toContain('"v1"'); // check never wrote
    } finally {
      rmSync(dir, { recursive: true, force: true });
    }
  });
});

describe("tsconfig sniff (allowImportingTsExtensions)", () => {
  // Build: <tmp>/(tsconfig.json…)/agent/instructions.md, generate, inspect the
  // emitted config import specifier. The sniff is JSONC-parsed and extends-
  // resolved — a textual match would get every case below wrong.
  const gen = (files: Record<string, string>): string => {
    const dir = mkdtempSync(join(tmpdir(), "june-agent-"));
    try {
      for (const [rel, content] of Object.entries(files)) {
        mkdirSync(dirname(join(dir, rel)), { recursive: true });
        writeFileSync(join(dir, rel), content);
      }
      mkdirSync(join(dir, "agent"), { recursive: true });
      writeFileSync(join(dir, "agent", "agent.ts"), "export default { name: \"ops\" };");
      return generateAgentModule(join(dir, "agent"))!.code;
    } finally {
      rmSync(dir, { recursive: true, force: true });
    }
  };

  test("a commented-out option does not count", () => {
    const code = gen({
      "tsconfig.json": `{\n  // "allowImportingTsExtensions": true,\n  "compilerOptions": {}\n}`,
    });
    expect(code).toContain(`from "./agent";`);
  });

  test("true inherited through extends (relative, .json omitted) is honored", () => {
    const code = gen({
      "tsconfig.base.json": `{ "compilerOptions": { "allowImportingTsExtensions": true } }`,
      "tsconfig.json": `{ "extends": "./tsconfig.base" }`,
    });
    expect(code).toContain(`from "./agent.ts";`);
  });

  test("true inherited from a bare-specifier extends (node_modules walk-up) is honored", () => {
    const code = gen({
      "node_modules/@acme/tsconfig/base.json": `{ "compilerOptions": { "allowImportingTsExtensions": true } }`,
      "tsconfig.json": `{ "extends": "@acme/tsconfig/base.json" }`,
    });
    expect(code).toContain(`from "./agent.ts";`);
  });

  test("the extending config's own value beats the base's", () => {
    const code = gen({
      "tsconfig.base.json": `{ "compilerOptions": { "allowImportingTsExtensions": true } }`,
      "tsconfig.json": `{ "extends": "./tsconfig.base", "compilerOptions": { "allowImportingTsExtensions": false } }`,
    });
    expect(code).toContain(`from "./agent";`);
  });
});

describe("unrecognized instructions variants", () => {
  test("a locale-suffixed filename warns loudly instead of sitting silently inert", () => {
    const dir = mkdtempSync(join(tmpdir(), "june-agent-"));
    const warns: string[] = [];
    const orig = console.warn;
    console.warn = (m: unknown) => void warns.push(String(m));
    try {
      const agentDir = join(dir, "agent");
      mkdirSync(agentDir);
      writeFileSync(join(agentDir, "instructions.md"), "base");
      writeFileSync(join(agentDir, "instructions.slack.zh-TW.md"), "locale variant");
      const r = generateAgentModule(agentDir)!;
      expect(r.code).not.toContain("locale variant"); // ignored today…
      expect(warns.join(" ")).toContain("instructions.slack.zh-TW.md"); // …but never silently
    } finally {
      console.warn = orig;
      rmSync(dir, { recursive: true, force: true });
    }
  });
});

describe("findAgentDir", () => {
  test("prefers app/agent (June app), falls back to ./agent (wrangler-first)", () => {
    const dir = mkdtempSync(join(tmpdir(), "june-agent-"));
    try {
      expect(findAgentDir(dir)).toBeNull();
      mkdirSync(join(dir, "agent"));
      expect(findAgentDir(dir)).toBe(join(dir, "agent"));
      mkdirSync(join(dir, "app", "agent"), { recursive: true });
      expect(findAgentDir(dir)).toBe(join(dir, "app", "agent"));
    } finally {
      rmSync(dir, { recursive: true, force: true });
    }
  });
});

describe("parity: compiled module ≡ native discovery", () => {
  test("assembleAgent(compiled) matches discoverAgent(dir) field for field", async () => {
    const { agentModule } = await import("./fixtures/agent-ops/_agent.gen");
    const compiled = await assembleAgent(agentModule, process.env);
    const discovered = await discoverAgent(FIXTURE);

    expect(compiled.name).toBe(discovered.name);
    expect(compiled.model).toBe(discovered.model);
    expect(compiled.description).toBe(discovered.description);
    expect(compiled.instructions).toBe(discovered.instructions);
    expect(compiled.tools.map((t) => t.spec.name).sort()).toEqual(discovered.tools.map((t) => t.spec.name).sort());
    expect(compiled.skills).toEqual(discovered.skills);
    expect(compiled.channels.map((c) => c.name).sort()).toEqual(discovered.channels.map((c) => c.name).sort());
    expect(compiled.channelInstructions).toEqual(discovered.channelInstructions);
  });
});

// ── The durable acceptance: skills mount on the DO target ──
// A fake ctx.storage (the same stand-in agent-durable.test.ts uses) is enough:
// the DO's turn engine dispatches read_skill exactly like any other tool.
async function fakeStorage(): Promise<DurableStorage & { close(): void }> {
  const db = await openLocalSqliteSync(":memory:");
  const sql: SqlStorage = {
    exec<T = Record<string, unknown>>(query: string, ...bindings: unknown[]) {
      const rows = db.query(query).all(...bindings) as T[];
      return { toArray: () => rows, one: () => rows[0]! };
    },
  };
  return {
    sql,
    transactionSync<T>(fn: () => T): T {
      db.exec("BEGIN");
      try { const r = fn(); db.exec("COMMIT"); return r; } catch (e) { db.exec("ROLLBACK"); throw e; }
    },
    close: () => db.close(),
  };
}

describe("compiled module on the durable target", () => {
  test("read_skill dispatches in a DO turn and hands the model the compiled skill body", async () => {
    const { agentModule } = await import("./fixtures/agent-ops/_agent.gen");
    const s = await fakeStorage();
    try {
      // Round 1: call read_skill. Round 2: report whether the tool RESULT carried
      // the skill's body — the assertion rides the final text, no DO internals.
      const model: Model = (msgs) => {
        const skill = msgs.find((m) => m.role === "tool" && m.name === "read_skill") as { result?: { body?: string } } | undefined;
        if (!skill) return replyStream({ text: "Loading the procedure.", toolCalls: [{ id: "c1", name: "read_skill", input: { name: "bulk_reorder" } }] });
        return replyStream({ text: skill.result?.body?.includes("Read the supplier list") ? "GOT_SKILL" : "NO_SKILL", toolCalls: [] });
      };
      const def = assembleDurable(agentModule);
      // the pre-composed prompt carries the skill index, when-to-use included
      expect(def.instructions).toContain(
        "- bulk_reorder: Reorder many items at once from a supplier list, checking stock first. — when to use: The user pastes a supplier list or asks to restock more than one item.",
      );

      // env rides along exactly like a real shell's `env: this.env` — the DO
      // resolves the compiled channel factories with it.
      const agent = new AgentDurableObject({ storage: s }, { ...def, model, env: { SLACK_SIGNING_SECRET: "s" } });
      const res = await agent.fetch(new Request("https://do/turn", { method: "POST", body: JSON.stringify({ userText: "restock", turnId: "t1" }) }));
      expect(await sseTurnFinalText(res)).toBe("GOT_SKILL");
    } finally {
      s.close();
    }
  });
});
