// Stage 3b — schema codegen. Introspect a migrated SQLite/D1 database and emit the
// `declare module "@junejs/juno"` augmentation that powers Stage 3a's `table()`
// inference. `june db types` writes the result to db/schema.d.ts. The schema of
// record stays in SQL (db/migrations/); this only DERIVES types from it, so the two
// never drift. Pure introspection — no schema DSL, nothing for the app to maintain.

import type { JuneDb } from "@junejs/core/resources";

// SQLite type affinity → TypeScript. Mirrors SQLite's affinity rules (the same five
// the engine itself applies), so a declared `varchar(40)` lands on `string`, `int`
// on `number`, etc. Unknown/blank affinity → Uint8Array (BLOB), the safe default.
function tsType(declared: string, notnull: number, pk: number): string {
  const t = declared.toUpperCase();
  let base: string;
  if (t.includes("INT")) base = "number"; // INTEGER affinity
  else if (t.includes("CHAR") || t.includes("CLOB") || t.includes("TEXT")) base = "string"; // TEXT
  else if (t === "" || t.includes("BLOB")) base = "Uint8Array"; // BLOB
  else if (t.includes("REAL") || t.includes("FLOA") || t.includes("DOUB")) base = "number"; // REAL
  else base = "number"; // NUMERIC (decimal / boolean / date stored as 0/1/epoch)
  // A column is nullable unless declared NOT NULL or part of the primary key (an
  // INTEGER PRIMARY KEY reports notnull=0 but is the never-null rowid alias).
  const nullable = notnull === 0 && pk === 0;
  return nullable ? `${base} | null` : base;
}

// Bare identifier if it's a safe JS property name, else a quoted key.
function propKey(name: string): string {
  return /^[A-Za-z_$][A-Za-z0-9_$]*$/.test(name) ? name : JSON.stringify(name);
}

type TableRow = { name: string };
type ColRow = { name: string; type: string; nn: number; pk: number };

// Introspect every user table (skipping sqlite internals + June's migration ledger)
// and return the augmentation file text. Reads only — never mutates the database.
export async function emitSchemaTypes(db: JuneDb): Promise<string> {
  const tables = await db.query<TableRow>(
    "select name from sqlite_master where type = 'table' " +
      "and name not like 'sqlite_%' and name <> '_june_migrations' order by name",
  );

  const ifaces: string[] = [];
  for (const { name } of tables) {
    // pragma_table_info(?) — the table-valued form takes a BOUND param, so no
    // identifier interpolation (injection-safe even for odd table names).
    const cols = await db.query<ColRow>(
      'select name, type, "notnull" as nn, pk from pragma_table_info(?)',
      [name],
    );
    const fields = cols
      .map((c) => `      ${propKey(c.name)}: ${tsType(c.type, c.nn, c.pk)};`)
      .join("\n");
    ifaces.push(`    ${propKey(name)}: {\n${fields}\n    };`);
  }

  return (
    "// Generated by `june db types`. Do not edit — re-run after a migration.\n" +
    'import "@junejs/juno";\n\n' +
    'declare module "@junejs/juno" {\n' +
    "  interface Schema {\n" +
    ifaces.join("\n") +
    "\n  }\n}\n"
  );
}
