// AUTO-GENERATED by June — do not edit. RSC route map.
import type React from "react";
import V0 from "./page.rsc";
export { CLIENT_MANIFEST as clientManifest } from "./_rsc-server.gen";
export const ROUTES: Record<string, React.ComponentType> = {
  "/": V0,
};
