// AUTO-GENERATED by June — do not edit. RSC document config.
export const DOC_CONFIG = {"site":{"name":"RSC"},"speculationRules":null,"speculationDelivery":"inline","viewTransitions":false} as const;
