// AUTO-GENERATED by `june build` — edit content/**/*.md, not this file.
export type ContentEntry = { slug: string; data: Record<string, string | string[]>; body: string; original: string; html: string; locale?: string };
export const DOCS: ContentEntry[] = [
  {
    "slug": "intro",
    "data": {
      "title": "Introduction",
      "date": "2026-06-16"
    },
    "body": "# Introduction\n\nThis is the **English** intro — the flat `content/docs/intro.md`, which is the\ndefault locale. A German variant lives at `content/docs/de/intro.md`; any locale\nwithout its own file falls back to this one.\n",
    "original": "---\ntitle: Introduction\ndate: 2026-06-16\n---\n\n# Introduction\n\nThis is the **English** intro — the flat `content/docs/intro.md`, which is the\ndefault locale. A German variant lives at `content/docs/de/intro.md`; any locale\nwithout its own file falls back to this one.\n",
    "html": "<h1>Introduction</h1>\n<p>This is the <strong>English</strong> intro — the flat <code>content/docs/intro.md</code>, which is the\ndefault locale. A German variant lives at <code>content/docs/de/intro.md</code>; any locale\nwithout its own file falls back to this one.</p>\n"
  }
];
const DOCS_L: Record<string, Record<string, ContentEntry>> = {
  "de": {
    "intro": {
      "slug": "intro",
      "data": {
        "title": "Einführung",
        "date": "2026-06-16"
      },
      "body": "# Einführung\n\nDies ist die **deutsche** Variante — `content/docs/de/intro.md`. Sie wird unter\n`/de/docs/intro` ausgeliefert; `ctx.locale` ist dann `\"de\"`.\n",
      "original": "---\ntitle: Einführung\ndate: 2026-06-16\n---\n\n# Einführung\n\nDies ist die **deutsche** Variante — `content/docs/de/intro.md`. Sie wird unter\n`/de/docs/intro` ausgeliefert; `ctx.locale` ist dann `\"de\"`.\n",
      "html": "<h1>Einführung</h1>\n<p>Dies ist die <strong>deutsche</strong> Variante — <code>content/docs/de/intro.md</code>. Sie wird unter\n<code>/de/docs/intro</code> ausgeliefert; <code>ctx.locale</code> ist dann <code>&quot;de&quot;</code>.</p>\n",
      "locale": "de"
    }
  }
};
export const doc = (slug: string, locale?: string, opts?: { fallback?: boolean }): ContentEntry | null => {
  const v = locale ? DOCS_L[locale]?.[slug] : undefined;
  if (v) return v;
  if (opts?.fallback === false) return null;
  const d = DOCS.find((p) => p.slug === slug) ?? null;
  if (process.env.NODE_ENV !== "production" && locale && DOCS_L[locale] && d) console.warn(`[june content] docs/${slug}: no "${locale}" variant — served default`);
  return d;
};
export const docs = (locale?: string): ContentEntry[] => locale && DOCS_L[locale] ? DOCS.map((p) => DOCS_L[locale]![p.slug] ?? p) : DOCS;
