// AUTO-GENERATED by `june gen` — edit messages/*.json, not this file.
import { defineMessages, t as rawT, type CompiledCatalog } from "@junejs/i18n";

const CATALOGS: Record<string, CompiledCatalog> = {"de":{"greeting":[{"type":0,"value":"Hallo, "},{"type":1,"value":"name"},{"type":0,"value":"!"}],"items":[{"type":6,"value":"n","options":{"one":{"value":[{"type":7},{"type":0,"value":" Eintrag"}]},"other":{"value":[{"type":7},{"type":0,"value":" Einträge"}]}},"offset":0,"pluralType":"cardinal"}]},"en":{"greeting":[{"type":0,"value":"Hello, "},{"type":1,"value":"name"},{"type":0,"value":"!"}],"items":[{"type":6,"value":"n","options":{"one":{"value":[{"type":7},{"type":0,"value":" item"}]},"other":{"value":[{"type":7},{"type":0,"value":" items"}]}},"offset":0,"pluralType":"cardinal"}]}};

defineMessages(CATALOGS, { defaultLocale: "en" });

// The message keys + their params, derived from the default locale's ICU ASTs.
export type Messages = {
  "greeting": { "name": string };
  "items": { "n": number };
};

// Typed translate: key AND params are checked against messages/*.json. A no-
// param message takes no second arg; a wrong/missing param is a compile error.
export const t = rawT as <K extends keyof Messages>(
  key: K,
  ...args: keyof Messages[K] extends never ? [] : [params: Messages[K]]
) => string;
