// `june build` — produce a Workers-ready bundle from a June app.
//
// What the dev server discovers at REQUEST time (filesystem routes,
// june.config.ts, content/ markdown), the build discovers ONCE and FREEZES into
// a static manifest fed to createWorker(). The built worker renders through the
// SAME pipeline as dev (pipeline.ts), so its surfaces are byte-equivalent —
// proven by test/parity.test.ts, not hoped for.
//
// Two entry points:
//   buildManifest(appRoot) → an in-process WorkerManifest (freeze only; used by
//     the parity test and by prerender — same render path as the bundle).
//   juneBuild(appRoot)     → the full build: content freeze + generated entry +
//     Rolldown bundle (workerd conditions, binary externals) +
//     prerender-through-the-worker + wrangler config.
//
// REMINDER #4: nothing in the worker graph may statically import node:*. The
// content freeze (content/*.md → app/_content.ts) is what removes fs from the
// dynamic route's graph; the worker reads frozen data, never the filesystem.

import { existsSync } from "node:fs";
import { mkdir, readdir, rm, writeFile } from "node:fs/promises";
import { basename, dirname, join, relative, sep } from "node:path";
import { pathToFileURL } from "node:url";

import { loadJuneConfig } from "./config-loader";
import { resolveAgent, resolveSpeculationRules } from "@junejs/core/config";
import { isRouteDefinition, type BrandedRoute } from "@junejs/core/route";
import type { DocumentConfig } from "@junejs/core/document";
import { collection } from "./content";
import { createWorker, type WorkerManifest } from "./worker";
import type { LayoutComponent } from "./pipeline";

export type BuildResult = {
  outFile: string;
  routes: string[];
  dynamicRoutes: string[];
  contentCollections: string[];
  prerendered: string[];
};

// The segment layout CHAIN root→leaf: every directory level (route groups
// included) may contribute a layout.* that wraps routes below it.
type RouteEntry = { path: string; file: string; dynamic: boolean; layouts: string[] };

const PAGE_BASENAMES = new Set(["page", "index"]);
const ROUTE_EXTS = [".tsx", ".jsx", ".ts", ".js"];

const isRouteGroup = (name: string) => /^\(.+\)$/.test(name);

function segmentFile(dir: string, base: string): string | undefined {
  return ROUTE_EXTS.map((e) => join(dir, `${base}${e}`)).find(existsSync);
}

// Walk app/ for page.* files → route paths (mirrors router.ts conventions:
// route groups vanish from URLs, `_`-prefixed entries are private), carrying the
// layout chain accumulated from each directory level.
export async function scanRoutes(
  appDir: string,
  dir = appDir,
  layouts: string[] = [],
  out: RouteEntry[] = [],
): Promise<RouteEntry[]> {
  const ownLayout = segmentFile(dir, "layout");
  const chain = ownLayout ? [...layouts, ownLayout] : layouts;
  const entries = await readdir(dir, { withFileTypes: true }).catch(() => []);
  for (const e of entries) {
    if (e.name.startsWith("_") || e.name.startsWith(".")) continue;
    const full = join(dir, e.name);
    if (e.isDirectory()) {
      await scanRoutes(appDir, full, chain, out);
      continue;
    }
    const ext = e.name.match(/\.[^.]+$/)?.[0] ?? "";
    if (!ROUTE_EXTS.includes(ext)) continue;
    if (!PAGE_BASENAMES.has(basename(e.name, ext))) continue;
    const relDir = relative(appDir, dir);
    const segments = relDir === "" ? [] : relDir.split(sep).filter((s) => !isRouteGroup(s));
    const path = "/" + segments.join("/");
    out.push({ path: path === "/" ? "/" : path, file: full, dynamic: /\[.+\]/.test(path), layouts: chain });
  }
  return out;
}

// content/<collection>/*.md → app/_content.ts (the build-time content manifest).
// This is the FREEZE that removes node:fs from the worker graph: routes import
// frozen entries from ./_content instead of reading the filesystem at request.
export async function generateContent(appRoot: string): Promise<string[]> {
  const contentDir = join(appRoot, "content");
  if (!existsSync(contentDir)) return [];
  const dirs = (await readdir(contentDir, { withFileTypes: true })).filter((e) => e.isDirectory());
  if (dirs.length === 0) return [];

  let out =
    "// AUTO-GENERATED by `june build` — edit content/**/*.md, not this file.\n" +
    "export type ContentEntry = { slug: string; data: Record<string, string | string[]>; body: string; original: string; html: string };\n";
  const names: string[] = [];
  for (const d of dirs) {
    const entries = collection(join(contentDir, d.name)).map(({ slug, data, body, original, html }) => ({
      slug,
      data,
      body,
      original,
      html,
    }));
    const constName = d.name.replace(/[^A-Za-z0-9]/g, "_").toUpperCase();
    // Singular finder name: posts → post, otherwise <name>Entry.
    const finder = d.name.endsWith("s") ? d.name.slice(0, -1) : `${d.name}Entry`;
    out += `export const ${constName}: ContentEntry[] = ${JSON.stringify(entries, null, 2)};\n`;
    out += `export const ${finder} = (slug: string): ContentEntry | null => ${constName}.find((p) => p.slug === slug) ?? null;\n`;
    names.push(d.name);
  }
  await writeFile(join(appRoot, "app", "_content.ts"), out);
  return names;
}

// Freeze june.config.ts → the serializable bits the worker inlines.
export async function freezeConfig(appRoot: string): Promise<{
  document: DocumentConfig;
  agent: WorkerManifest["agent"];
  earlyHints: string[];
}> {
  const cfg = await loadJuneConfig(appRoot);
  return {
    document: {
      site: cfg.site ?? {},
      speculationRules: resolveSpeculationRules(cfg.speculation ?? undefined),
      speculationDelivery: "inline",
      viewTransitions: cfg.viewTransitions ?? true,
    },
    agent: resolveAgent(cfg.agent),
    earlyHints: cfg.earlyHints ?? [],
  };
}

async function importLayout(file: string): Promise<LayoutComponent | null> {
  const mod = (await import(pathToFileURL(file).href)) as { default?: LayoutComponent };
  return typeof mod.default === "function" ? mod.default : null;
}

// The FREEZE, in-process: import route modules + layouts, build the manifest a
// createWorker() can run immediately. Used by prerender and by the parity test
// (its render path is identical to the Rolldown-bundled worker).
export async function buildManifest(appRoot: string): Promise<WorkerManifest> {
  const appDir = join(appRoot, "app");
  const frozen = await freezeConfig(appRoot);
  const scanned = (await scanRoutes(appDir)).sort((a, b) => a.path.localeCompare(b.path));

  const layoutCache = new Map<string, LayoutComponent | null>();
  const componentsFor = async (files: string[]): Promise<LayoutComponent[]> => {
    const chain: LayoutComponent[] = [];
    for (const f of files) {
      if (!layoutCache.has(f)) layoutCache.set(f, await importLayout(f));
      const c = layoutCache.get(f) ?? null;
      if (c) chain.push(c);
    }
    return chain;
  };

  const routes: Record<string, BrandedRoute> = {};
  const dynamicRoutes: Array<{ pattern: string; def: BrandedRoute }> = [];
  const layoutChains: Record<string, LayoutComponent[]> = {};

  for (const r of scanned) {
    const mod = (await import(pathToFileURL(r.file).href)) as { default?: unknown };
    if (!isRouteDefinition(mod.default)) continue;
    const chain = await componentsFor(r.layouts);
    if (r.dynamic) {
      dynamicRoutes.push({ pattern: r.path, def: mod.default });
      layoutChains[r.path] = chain;
    } else {
      routes[r.path] = mod.default;
      layoutChains[r.path] = chain;
    }
  }

  return {
    routes,
    dynamicRoutes,
    layoutChains,
    document: frozen.document,
    agent: frozen.agent,
    earlyHints: frozen.earlyHints,
  };
}

function importPath(fromDir: string, file: string): string {
  const p = relative(fromDir, file).split(sep).join("/").replace(/\.[^.]+$/, "");
  return p.startsWith(".") ? p : `./${p}`;
}

export async function juneBuild(
  appRoot: string,
  options: { outDir?: string; external?: string[] } = {},
): Promise<BuildResult> {
  const appDir = join(appRoot, "app");
  if (!existsSync(appDir)) throw new Error(`no app/ directory in ${appRoot} — is this a June app?`);
  const genDir = join(appRoot, ".june");
  const outDir = options.outDir ?? join(appRoot, "dist");
  await mkdir(genDir, { recursive: true });
  await rm(outDir, { recursive: true, force: true }); // stale chunks must not ship

  const contentCollections = await generateContent(appRoot);
  const routes = (await scanRoutes(appDir)).sort((a, b) => a.path.localeCompare(b.path));
  if (routes.length === 0) throw new Error(`no page.* routes found under ${appDir}`);

  const frozen = await freezeConfig(appRoot);

  // ---- generated entry -----------------------------------------------------
  const imports: string[] = [`import { createWorker } from "@junejs/server/worker";`];
  const statics: string[] = [];
  const dynamics: string[] = [];
  const layoutIds = new Map<string, string>();
  const layoutId = (file: string) => {
    let id = layoutIds.get(file);
    if (!id) {
      id = `L${layoutIds.size}`;
      layoutIds.set(file, id);
      imports.push(`import ${id} from ${JSON.stringify(importPath(genDir, file))};`);
    }
    return id;
  };
  const chains: string[] = [];
  routes.forEach((r, i) => {
    imports.push(`import r${i} from ${JSON.stringify(importPath(genDir, r.file))};`);
    if (r.dynamic) dynamics.push(`    { pattern: ${JSON.stringify(r.path)}, def: r${i} },`);
    else statics.push(`    ${JSON.stringify(r.path)}: r${i},`);
    chains.push(`    ${JSON.stringify(r.path)}: [${r.layouts.map(layoutId).join(", ")}],`);
  });

  const entry = `// AUTO-GENERATED by \`june build\` — do not edit. Regenerate: june build .
${imports.join("\n")}

export default createWorker({
  routes: {
${statics.join("\n")}
  },
  dynamicRoutes: [
${dynamics.join("\n")}
  ],
  layoutChains: {
${chains.join("\n")}
  },
  document: ${JSON.stringify(frozen.document, null, 2).replace(/\n/g, "\n  ")},
  agent: ${JSON.stringify(frozen.agent)},
  earlyHints: ${JSON.stringify(frozen.earlyHints)},
});
`;
  const entryFile = join(genDir, "worker-entry.tsx");
  await writeFile(entryFile, entry);

  // ---- bundle (Rolldown; self-contained ESM for workerd) -------------------
  const { rolldown } = await import("rolldown");
  const bundle = await rolldown({
    input: entryFile,
    cwd: appRoot,
    platform: "browser", // workerd's surface is web-standard; no node:* in the graph
    external: (id: string) => {
      // Binary assets stay external — wrangler's CompiledWasm/Data rules own them.
      if (/\.(wasm|ttf|otf|woff2?|png|jpe?g|avif|webp)$/.test(id)) return true;
      const list = options.external ?? [];
      return list.some((e) => id === e || id.startsWith(`${e}/`));
    },
    resolve: {
      // Conditions BAKED at build (workerd has no runtime conditions, reminder #3).
      conditionNames: ["workerd", "edge", "import", "default"],
    },
  });
  const result = await bundle.write({ dir: outDir, format: "esm", entryFileNames: "worker.js" });
  await bundle.close();
  const outFile = join(
    outDir,
    result.output.find((o) => o.type === "chunk" && o.isEntry)?.fileName ?? "worker.js",
  );

  // ---- prerender: opted-in static routes render THROUGH the worker ---------
  // Same render path as the bundle (createWorker over the frozen manifest), so
  // what ships is what the parity test verified.
  const prerendered: string[] = [];
  const manifest = await buildManifest(appRoot);
  const worker = createWorker(manifest);
  const assetsDir = join(outDir, "assets");
  let hasAssets = false;

  for (const r of routes.filter((x) => !x.dynamic)) {
    const def = manifest.routes[r.path];
    if (!def || !def.prerender) continue;
    const stem = r.path === "/" ? "index" : r.path.slice(1);
    const targets: Array<[string, string]> = [[r.path, `${stem}.html`]];
    if (r.path !== "/") {
      targets.push([`${r.path}.md`, `${stem}.md`]);
      if (typeof def.json === "function") targets.push([`${r.path}.json`, `${stem}.json`]);
    }
    for (const [reqPath, file] of targets) {
      const res = await worker.fetch(new Request(`https://prerender.june${reqPath}`));
      if (!res.ok) throw new Error(`prerender ${reqPath} → ${res.status}`);
      const dest = join(assetsDir, file);
      await mkdir(dirname(dest), { recursive: true });
      await writeFile(dest, Buffer.from(await res.arrayBuffer()));
    }
    prerendered.push(r.path);
    hasAssets = true;
  }

  // ---- wrangler config (only when the app doesn't manage its own) ----------
  if (!existsSync(join(appRoot, "wrangler.toml")) && !existsSync(join(appRoot, "wrangler.jsonc"))) {
    const pkgPath = join(appRoot, "package.json");
    const pkg = existsSync(pkgPath)
      ? (JSON.parse(await Bun.file(pkgPath).text()) as { name?: string })
      : {};
    await writeFile(
      join(outDir, "wrangler.jsonc"),
      JSON.stringify(
        {
          name: (pkg.name ?? basename(appRoot)).replace(/[^a-z0-9-]/gi, "-").toLowerCase(),
          main: "./worker.js",
          compatibility_date: "2025-01-01",
          compatibility_flags: ["nodejs_compat"],
          ...(hasAssets ? { assets: { directory: "./assets" } } : {}),
        },
        null,
        2,
      ) + "\n",
    );
  }

  return {
    outFile,
    routes: routes.filter((r) => !r.dynamic).map((r) => r.path),
    dynamicRoutes: routes.filter((r) => r.dynamic).map((r) => r.path),
    contentCollections,
    prerendered,
  };
}
