// `june build` — produce a Workers-ready bundle from a June app.
//
// What the dev server discovers at REQUEST time (filesystem routes,
// june.config.ts, content/ markdown), the build discovers ONCE and FREEZES into
// a static manifest fed to createWorker(). The built worker renders through the
// SAME pipeline as dev (pipeline.ts), so its surfaces are byte-equivalent —
// proven by test/parity.test.ts, not hoped for.
//
// Two entry points:
//   buildManifest(appRoot) → an in-process WorkerManifest (freeze only; used by
//     the parity test and by prerender — same render path as the bundle).
//   juneBuild(appRoot)     → the full build: content freeze + generated entry +
//     Rolldown bundle (workerd conditions, binary externals) +
//     prerender-through-the-worker + wrangler config.
//
// REMINDER #4: nothing in the worker graph may statically import node:*. The
// content freeze (content/*.md → app/_content.ts) is what removes fs from the
// dynamic route's graph; the worker reads frozen data, never the filesystem.

import { createHash } from "node:crypto";
import { existsSync } from "node:fs";
import { mkdir, readdir, rm, writeFile } from "node:fs/promises";
import { basename, dirname, join, relative, sep } from "node:path";
import { pathToFileURL } from "node:url";

import { loadJuneConfig } from "./config-loader";
import { resolveAgent, resolveSpeculationRules } from "@junejs/core/config";
import { buildLinkHeader } from "@junejs/core/discovery";
import { routeFromModule, type BrandedRoute } from "@junejs/core/route";
import { workers, type JuneAdapter, type ResourcePlan } from "./adapter";
import type { DocumentConfig } from "@junejs/core/document";
import { collection } from "./content";
import { createWorker, type WorkerManifest } from "./worker";
import { findExtraFile } from "./router";
import type { ExtraHandler, LayoutComponent, LoadingComponent } from "./pipeline";
import { findClientEntry, bundleClientToFile, CLIENT_SCRIPT_URL } from "./client-bundle";
import { findGlobalCss, minifyCss, processCss, STYLES_URL } from "./css";
import { buildModuleCss, rolldownCssModulesPlugin, registerCssModules } from "./css-modules";

export type BuildResult = {
  outFile: string;
  routes: string[];
  dynamicRoutes: string[];
  contentCollections: string[];
  prerendered: string[];
};

// The segment layout CHAIN root→leaf: every directory level (route groups
// included) may contribute a layout.* that wraps routes below it.
type RouteEntry = {
  path: string;
  file: string;
  dynamic: boolean;
  layouts: string[];
  loading?: string; // nearest loading.tsx up the tree → streaming Suspense fallback
};

const PAGE_BASENAMES = new Set(["page", "index"]);
const ROUTE_EXTS = [".tsx", ".jsx", ".ts", ".js"];

const isRouteGroup = (name: string) => /^\(.+\)$/.test(name);

function segmentFile(dir: string, base: string): string | undefined {
  return ROUTE_EXTS.map((e) => join(dir, `${base}${e}`)).find(existsSync);
}

// Walk app/ for page.* files → route paths (mirrors router.ts conventions:
// route groups vanish from URLs, `_`-prefixed entries are private), carrying the
// layout chain accumulated from each directory level.
export async function scanRoutes(
  appDir: string,
  dir = appDir,
  layouts: string[] = [],
  out: RouteEntry[] = [],
  loading?: string,
): Promise<RouteEntry[]> {
  const ownLayout = segmentFile(dir, "layout");
  const chain = ownLayout ? [...layouts, ownLayout] : layouts;
  const nearestLoading = segmentFile(dir, "loading") ?? loading;
  const entries = await readdir(dir, { withFileTypes: true }).catch(() => []);
  for (const e of entries) {
    if (e.name.startsWith("_") || e.name.startsWith(".")) continue;
    const full = join(dir, e.name);
    if (e.isDirectory()) {
      await scanRoutes(appDir, full, chain, out, nearestLoading);
      continue;
    }
    const ext = e.name.match(/\.[^.]+$/)?.[0] ?? "";
    if (!ROUTE_EXTS.includes(ext)) continue;
    if (!PAGE_BASENAMES.has(basename(e.name, ext))) continue;
    const relDir = relative(appDir, dir);
    const segments = relDir === "" ? [] : relDir.split(sep).filter((s) => !isRouteGroup(s));
    const path = "/" + segments.join("/");
    out.push({
      path: path === "/" ? "/" : path,
      file: full,
      dynamic: /\[.+\]/.test(path),
      layouts: chain,
      loading: nearestLoading,
    });
  }
  return out;
}

// content/<collection>/*.md → app/_content.ts (the build-time content manifest).
// This is the FREEZE that removes node:fs from the worker graph: routes import
// frozen entries from ./_content instead of reading the filesystem at request.
export async function generateContent(appRoot: string): Promise<string[]> {
  const contentDir = join(appRoot, "content");
  if (!existsSync(contentDir)) return [];
  const dirs = (await readdir(contentDir, { withFileTypes: true })).filter((e) => e.isDirectory());
  if (dirs.length === 0) return [];

  let out =
    "// AUTO-GENERATED by `june build` — edit content/**/*.md, not this file.\n" +
    "export type ContentEntry = { slug: string; data: Record<string, string | string[]>; body: string; original: string; html: string };\n";
  const names: string[] = [];
  for (const d of dirs) {
    const entries = collection(join(contentDir, d.name)).map(({ slug, data, body, original, html }) => ({
      slug,
      data,
      body,
      original,
      html,
    }));
    const constName = d.name.replace(/[^A-Za-z0-9]/g, "_").toUpperCase();
    // Singular finder name: posts → post, otherwise <name>Entry.
    const finder = d.name.endsWith("s") ? d.name.slice(0, -1) : `${d.name}Entry`;
    out += `export const ${constName}: ContentEntry[] = ${JSON.stringify(entries, null, 2)};\n`;
    out += `export const ${finder} = (slug: string): ContentEntry | null => ${constName}.find((p) => p.slug === slug) ?? null;\n`;
    names.push(d.name);
  }
  await writeFile(join(appRoot, "app", "_content.ts"), out);
  return names;
}

// Freeze june.config.ts → the serializable bits the worker inlines.
export async function freezeConfig(appRoot: string): Promise<{
  document: DocumentConfig;
  agent: WorkerManifest["agent"];
  earlyHints: string[];
  buildExternal: string[];
}> {
  const cfg = await loadJuneConfig(appRoot);
  // An app with a client entry gets the islands runtime URL frozen into its
  // document. Detected HERE (not just in juneBuild) so the prerender path —
  // which re-freezes through buildManifest — sets the SAME clientScript, keeping
  // prerendered pages byte-equivalent to the live worker (parity).
  const hasClient = findClientEntry(join(appRoot, "app")) !== undefined;
  const hasCss = findGlobalCss(join(appRoot, "app")) !== null;
  return {
    document: {
      site: cfg.site ?? {},
      speculationRules: resolveSpeculationRules(cfg.speculation ?? undefined),
      speculationDelivery: "inline",
      viewTransitions: cfg.viewTransitions ?? true,
      clientRouter: cfg.clientRouter ?? false,
      clientScript: hasClient ? CLIENT_SCRIPT_URL : null,
      styles: hasCss ? STYLES_URL : null,
    },
    agent: resolveAgent(cfg.agent),
    earlyHints: cfg.earlyHints ?? [],
    buildExternal: cfg.build?.external ?? [],
  };
}

async function importLayout(file: string): Promise<LayoutComponent | null> {
  const mod = (await import(pathToFileURL(file).href)) as { default?: LayoutComponent };
  return typeof mod.default === "function" ? mod.default : null;
}

// The FREEZE, in-process: import route modules + layouts, build the manifest a
// createWorker() can run immediately. Used by prerender and by the parity test
// (its render path is identical to the Rolldown-bundled worker).
export async function buildManifest(appRoot: string): Promise<WorkerManifest> {
  const appDir = join(appRoot, "app");
  const frozen = await freezeConfig(appRoot);
  const scanned = (await scanRoutes(appDir)).sort((a, b) => a.path.localeCompare(b.path));

  const layoutCache = new Map<string, LayoutComponent | null>();
  const componentsFor = async (files: string[]): Promise<LayoutComponent[]> => {
    const chain: LayoutComponent[] = [];
    for (const f of files) {
      if (!layoutCache.has(f)) layoutCache.set(f, await importLayout(f));
      const c = layoutCache.get(f) ?? null;
      if (c) chain.push(c);
    }
    return chain;
  };

  const loadingCache = new Map<string, LoadingComponent | null>();
  const loadingFor = async (file?: string): Promise<LoadingComponent | undefined> => {
    if (!file) return undefined;
    if (!loadingCache.has(file)) loadingCache.set(file, await importLayout(file) as LoadingComponent | null);
    return loadingCache.get(file) ?? undefined;
  };

  const routes: Record<string, BrandedRoute> = {};
  const dynamicRoutes: Array<{ pattern: string; def: BrandedRoute }> = [];
  const layoutChains: Record<string, LayoutComponent[]> = {};
  const loadings: Record<string, LoadingComponent> = {};

  for (const r of scanned) {
    const mod = await import(pathToFileURL(r.file).href);
    const def = routeFromModule(mod);
    if (!def) continue;
    const chain = await componentsFor(r.layouts);
    const loading = await loadingFor(r.loading);
    if (r.dynamic) {
      dynamicRoutes.push({ pattern: r.path, def });
      layoutChains[r.path] = chain;
    } else {
      routes[r.path] = def;
      layoutChains[r.path] = chain;
    }
    if (loading) loadings[r.path] = loading;
  }

  let extra: ExtraHandler | undefined;
  const extraFile = findExtraFile(appDir);
  if (extraFile) {
    const mod = (await import(pathToFileURL(extraFile).href)) as { default?: unknown };
    if (typeof mod.default === "function") extra = mod.default as ExtraHandler;
  }

  return {
    routes,
    dynamicRoutes,
    layoutChains,
    loadings,
    document: frozen.document,
    agent: frozen.agent,
    earlyHints: frozen.earlyHints,
    extra,
  };
}

function importPath(fromDir: string, file: string): string {
  const p = relative(fromDir, file).split(sep).join("/").replace(/\.[^.]+$/, "");
  return p.startsWith(".") ? p : `./${p}`;
}

export async function juneBuild(
  appRoot: string,
  options: { outDir?: string; external?: string[] } = {},
): Promise<BuildResult> {
  const appDir = join(appRoot, "app");
  if (!existsSync(appDir)) throw new Error(`no app/ directory in ${appRoot} — is this a June app?`);
  const genDir = join(appRoot, ".june");
  const outDir = options.outDir ?? join(appRoot, "dist");
  await mkdir(genDir, { recursive: true });
  await rm(outDir, { recursive: true, force: true }); // stale chunks must not ship

  const contentCollections = await generateContent(appRoot);
  const routes = (await scanRoutes(appDir)).sort((a, b) => a.path.localeCompare(b.path));
  if (routes.length === 0) throw new Error(`no page.* routes found under ${appDir}`);

  const frozen = await freezeConfig(appRoot);
  // The deploy adapter packages the portable build for its target (default:
  // built-in workers()). It contributes the entry's export wrapper + emits the
  // deploy config.
  const fullConfig = await loadJuneConfig(appRoot);
  const adapter = (fullConfig.deploy?.adapter as JuneAdapter | undefined) ?? workers();

  // Fail fast on a config the target can't honor (e.g. Vercel has no D1) BEFORE
  // the expensive bundle/prerender. The adapter only needs to know which
  // resources are declared, so a presence-only plan suffices here.
  adapter.validate?.({
    plan: { db: fullConfig.resources?.db ? { binding: "DB", databaseName: "" } : undefined },
    config: fullConfig,
  });

  // Compile the global stylesheet ONCE and content-hash it: the built worker and
  // prerendered HTML link `/global.<hash>.css`, served immutable (cache forever,
  // a content change ships a new URL → no revalidation, no stale window). Dev
  // keeps the stable /global.css; only the asset HREF diverges dev↔built, never
  // render semantics. freezeConfig + buildManifest both default styles to the
  // stable URL — override both with the hashed one.
  const cssOut = await processCss(appDir, { minify: true });
  let cssAsset: string | null = null;
  if (cssOut !== null) {
    const hash = createHash("sha256").update(cssOut).digest("hex").slice(0, 8);
    cssAsset = `_june/global.${hash}.css`; // under the reserved /_june/ prefix
    frozen.document.styles = `/${cssAsset}`;
  }

  // CSS Modules: glob + transform app/**/*.module.css ONCE → the per-file class
  // maps (the bundlers + dev loaders look these up) AND the collected stylesheet,
  // which is content-hashed + emitted + linked just like global.css.
  const { maps: cssModuleMaps, css: rawModuleCss } = await buildModuleCss(appDir, appRoot);
  // Minify for build (dev serves it readable). Scoped class names are untouched,
  // so the hashed sheet still matches the maps the bundlers/loaders hand out.
  const moduleCss = rawModuleCss === null ? null : await minifyCss(rawModuleCss, "modules.css");
  let moduleCssAsset: string | null = null;
  if (moduleCss !== null) {
    const hash = createHash("sha256").update(moduleCss).digest("hex").slice(0, 8);
    moduleCssAsset = `_june/modules.${hash}.css`;
    frozen.document.moduleStyles = `/${moduleCssAsset}`;
  }

  // Same for the client islands bundle: build + content-hash it NOW (before the
  // entry codegen + prerender) so both freeze the hashed /_june/client.<hash>.js
  // and it can be served immutable. The asset is written here. The client may
  // import .module.css too, so it gets the same module maps.
  const assetsDir = join(outDir, "assets");
  const clientEntry = findClientEntry(appDir);
  let clientAsset: string | null = null;
  if (clientEntry) {
    clientAsset = await bundleClientToFile(clientEntry, appRoot, assetsDir, cssModuleMaps);
    frozen.document.clientScript = `/${clientAsset}`;
  }

  // Declared resources become two things: a build-time plan (→ platform bindings
  // the adapter emits) and a runtime provider wired into the generated entry.
  // A resource-less app imports no config and emits no bindings, so its output
  // is byte-identical to before — the parity guarantee holds.
  const resourcesCfg = fullConfig.resources;
  const hasResources = !!(resourcesCfg?.db || resourcesCfg?.kv || resourcesCfg?.blob);

  // ---- generated entry -----------------------------------------------------
  // Routes are namespace-imported and adapted with routeFromModule, so the
  // multi-export page shape (default view + named loader/json/md) and the legacy
  // route({}) default export both work.
  const imports: string[] = [
    `import { createWorker } from "@junejs/server/worker";`,
    `import { routeFromModule } from "@junejs/core/route";`,
  ];
  const statics: string[] = [];
  const dynamics: string[] = [];
  const layoutIds = new Map<string, string>();
  const layoutId = (file: string) => {
    let id = layoutIds.get(file);
    if (!id) {
      id = `L${layoutIds.size}`;
      layoutIds.set(file, id);
      imports.push(`import ${id} from ${JSON.stringify(importPath(genDir, file))};`);
    }
    return id;
  };
  const loadingIds = new Map<string, string>();
  const loadingId = (file: string) => {
    let id = loadingIds.get(file);
    if (!id) {
      id = `Ld${loadingIds.size}`;
      loadingIds.set(file, id);
      imports.push(`import ${id} from ${JSON.stringify(importPath(genDir, file))};`);
    }
    return id;
  };
  const chains: string[] = [];
  const loadings: string[] = [];
  routes.forEach((r, i) => {
    imports.push(`import * as r${i} from ${JSON.stringify(importPath(genDir, r.file))};`);
    if (r.dynamic) dynamics.push(`    { pattern: ${JSON.stringify(r.path)}, def: routeFromModule(r${i}) },`);
    else statics.push(`    ${JSON.stringify(r.path)}: routeFromModule(r${i}),`);
    chains.push(`    ${JSON.stringify(r.path)}: [${r.layouts.map(layoutId).join(", ")}],`);
    if (r.loading) loadings.push(`    ${JSON.stringify(r.path)}: ${loadingId(r.loading)},`);
  });

  const builtExtraFile = findExtraFile(appDir);
  if (builtExtraFile) {
    imports.push(`import extra from ${JSON.stringify(importPath(genDir, builtExtraFile))};`);
  }

  // The Link header is frozen here from the same builder the pipeline uses, so
  // the static and dynamic surfaces advertise identically. The adapter wraps the
  // portable pipeline for its target (workers() → withAssets).
  const linkHeader = buildLinkHeader(frozen.agent);
  const adapterEntry = adapter.entry({ linkHeader });

  // Resources (when declared) are bound from the worker's env (env.DB → D1) by
  // an env-aware provider. We bake a pure FLAGS descriptor — never importing the
  // user's config, which would drag the host-only sqlite()/dev server into the
  // workerd bundle. Only emitted when something is declared, so resource-less
  // bundles stay byte-identical (and host code never enters the graph).
  const resourceFlags = {
    db: !!resourcesCfg?.db,
    kv: !!resourcesCfg?.kv,
    blob: !!resourcesCfg?.blob,
  };
  if (hasResources) {
    imports.push(`import { bindWorkerResources } from "@junejs/server/resources";`);
  }
  const resourcesField = hasResources
    ? `\n  resources: bindWorkerResources(${JSON.stringify(resourceFlags)}),`
    : "";
  const entry = `// AUTO-GENERATED by \`june build\` — do not edit. Regenerate: june build .
${adapterEntry.imports.join("\n")}
${imports.join("\n")}

const pipeline = createWorker({
  routes: {
${statics.join("\n")}
  },
  dynamicRoutes: [
${dynamics.join("\n")}
  ],
  layoutChains: {
${chains.join("\n")}
  },
  loadings: {
${loadings.join("\n")}
  },
  document: ${JSON.stringify(frozen.document, null, 2).replace(/\n/g, "\n  ")},
  agent: ${JSON.stringify(frozen.agent)},
  earlyHints: ${JSON.stringify(frozen.earlyHints)},${builtExtraFile ? "\n  extra," : ""}${resourcesField}
});

${adapterEntry.wrap("pipeline")}
`;
  const entryFile = join(genDir, "worker-entry.tsx");
  await writeFile(entryFile, entry);

  // ---- bundle (Rolldown; self-contained ESM for workerd) -------------------
  const { rolldown } = await import("rolldown");
  const bundle = await rolldown({
    input: entryFile,
    cwd: appRoot,
    platform: "browser", // workerd's surface is web-standard; no node:* in the graph
    plugins: [rolldownCssModulesPlugin(cssModuleMaps)], // .module.css → scoped class map
    external: (id: string) => {
      // Binary assets stay external — wrangler's CompiledWasm/Data rules own them.
      if (/\.(wasm|ttf|otf|woff2?|png|jpe?g|avif|webp)$/.test(id)) return true;
      // config build.external: packages wrangler must bundle itself (its own
      // esbuild owns their .wasm/asset rules — e.g. workers-og).
      const list = options.external ?? frozen.buildExternal;
      return list.some((e) => id === e || id.startsWith(`${e}/`));
    },
    resolve: {
      // Conditions BAKED at build (the target has no runtime conditions, reminder
      // #3). Adapter-owned: workers → workerd, vercel → edge-light.
      conditionNames: adapter.conditions,
    },
  });
  const result = await bundle.write({ dir: outDir, format: "esm", entryFileNames: "worker.js" });
  await bundle.close();
  const outFile = join(
    outDir,
    result.output.find((o) => o.type === "chunk" && o.isEntry)?.fileName ?? "worker.js",
  );

  // ---- prerender: opted-in static routes render THROUGH the worker ---------
  // Same render path as the bundle (createWorker over the frozen manifest), so
  // what ships is what the parity test verified.
  const prerendered: string[] = [];
  // Prerender imports route modules in-process, so the runtime CSS-Modules
  // interceptor must be active for any route that imports a .module.css.
  await registerCssModules(cssModuleMaps);
  const manifest = await buildManifest(appRoot);
  if (cssAsset) manifest.document.styles = `/${cssAsset}`; // prerendered HTML links the hashed sheet
  if (clientAsset) manifest.document.clientScript = `/${clientAsset}`;
  if (moduleCssAsset) manifest.document.moduleStyles = `/${moduleCssAsset}`;
  const worker = createWorker(manifest);
  let hasAssets = false;

  for (const r of routes.filter((x) => !x.dynamic)) {
    const def = manifest.routes[r.path];
    if (!def || !def.prerender) continue;
    const stem = r.path === "/" ? "index" : r.path.slice(1);
    // The homepage's projection requests are `/.md` / `/.json` (negotiate strips
    // the ext back to `/`); withAssets serves them for `Accept: text/markdown`.
    const mdReq = r.path === "/" ? "/.md" : `${r.path}.md`;
    const jsonReq = r.path === "/" ? "/.json" : `${r.path}.json`;
    const targets: Array<[string, string]> = [
      [r.path, `${stem}.html`],
      [mdReq, `${stem}.md`],
    ];
    if (typeof def.json === "function") targets.push([jsonReq, `${stem}.json`]);
    for (const [reqPath, file] of targets) {
      const res = await worker.fetch(new Request(`https://prerender.june${reqPath}`));
      if (!res.ok) throw new Error(`prerender ${reqPath} → ${res.status}`);
      const dest = join(assetsDir, file);
      await mkdir(dirname(dest), { recursive: true });
      await writeFile(dest, Buffer.from(await res.arrayBuffer()));
    }
    prerendered.push(r.path);
    hasAssets = true;
  }

  // ---- client islands bundle: built + content-hashed earlier (assets/_june/
  //      client.<hash>.js, frozen into the document). No entry → page ships zero JS.
  if (clientAsset) hasAssets = true;

  // ---- global stylesheet: app/global.css → assets/global.css ---------------
  // Served at /global.css; the frozen document already <link>s it. Compiled
  // (Tailwind) or passed through (plain CSS). No file → no asset.
  if (cssOut !== null && cssAsset) {
    const dest = join(assetsDir, cssAsset);
    await mkdir(dirname(dest), { recursive: true }); // cssAsset includes the _june/ subdir
    await writeFile(dest, cssOut);
    hasAssets = true;
  }

  // ---- collected CSS Modules: app/**/*.module.css → assets/_june/modules.<hash>.css
  if (moduleCss !== null && moduleCssAsset) {
    const dest = join(assetsDir, moduleCssAsset);
    await mkdir(dirname(dest), { recursive: true });
    await writeFile(dest, moduleCss);
    hasAssets = true;
  }

  // ---- deploy structure (adapter-owned: wrangler.jsonc for workers) --------
  const pkgPath = join(appRoot, "package.json");
  const pkgName = existsSync(pkgPath)
    ? (JSON.parse(await Bun.file(pkgPath).text()) as { name?: string }).name
    : undefined;
  const defaultName = (pkgName ?? basename(appRoot)).replace(/[^a-z0-9-]/gi, "-").toLowerCase();
  // A declared `db` → a D1 binding named DB (the name bindWorkerResources reads).
  const plan: ResourcePlan = resourcesCfg?.db
    ? { db: { binding: "DB", databaseName: `${defaultName}-db` } }
    : {};
  await adapter.emit({ appRoot, outDir, hasAssets, linkHeader, config: fullConfig, plan, defaultName });
  if (plan.db) {
    console.log(
      `  ↳ d1 binding "${plan.db.binding}" emitted — set database_id in wrangler.jsonc (wrangler d1 create ${plan.db.databaseName})`,
    );
  }

  return {
    outFile,
    routes: routes.filter((r) => !r.dynamic).map((r) => r.path),
    dynamicRoutes: routes.filter((r) => r.dynamic).map((r) => r.path),
    contentCollections,
    prerendered,
  };
}
