// Auto-generate the island registry by scanning "use client" island() modules,
// so the author never hand-writes the `{ name: () => import("./Island") }` map.
//
// Scans app/** for modules that (a) start with the "use client" directive AND
// (b) use `island()` from @junejs/core/poc-islands, and writes app/_islands.gen.ts:
//
//   export const ISLAND_LOADERS = {
//     "Counter": () => import("./poc/Counter"),
//     "Tabs":    () => import("./poc/Tabs"),
//   };
//
// The KEY is the module's EXPORT name; importing the module runs its `island()`
// call, which self-registers the component under its runtime name. Those must
// agree — the marker the server stamps (the island's name) is what the client
// looks up. So the convention is: an island's name == its export name (the React
// default — `export const Counter = island(function Counter() {…})` satisfies it
// for free; otherwise pass `island(C, { name })`).
//
// Over-inclusion is harmless: a loader whose name no marker references is never
// called, so no chunk for an unused export is ever fetched.
//
// Host-coupled (node:fs), so it lives in @junejs/server, never the contract layer.
import { readdirSync, readFileSync, statSync, writeFileSync } from "node:fs";
import { join, relative } from "node:path";

export const ISLAND_REGISTRY_FILE = "_islands.gen.ts";

function walk(dir: string): string[] {
  return readdirSync(dir).flatMap((name) => {
    const p = join(dir, name);
    return statSync(p).isDirectory() ? walk(p) : [p];
  });
}

// True iff the first real statement (skipping blanks + line comments) is the
// directive — the same rule the bundler uses to treat a module as client.
function firstStatementIsDirective(src: string, directive: string): boolean {
  for (const line of src.split("\n")) {
    const t = line.trim();
    if (!t || t.startsWith("//")) continue;
    return t.startsWith(`"${directive}"`) || t.startsWith(`'${directive}'`);
  }
  return false;
}

// The named exports of a module (skipping `export default` and `export type`).
function exportNames(src: string): string[] {
  const names: string[] = [];
  for (const line of src.split("\n")) {
    const t = line.trim();
    const decl = t.match(/^export\s+(?:async\s+)?(?:function|const|let|var|class)\s+([A-Za-z0-9_$]+)/);
    if (decl) names.push(decl[1]!);
    const named = t.match(/^export\s*\{([^}]*)\}/); // `export type { … }` won't match (the `type` breaks it)
    if (named) {
      for (const part of named[1]!.split(",")) {
        const e = part.split(" as ").pop()?.trim();
        if (e) names.push(e);
      }
    }
  }
  return names;
}

// Write app/_islands.gen.ts. Returns the number of island loaders emitted.
export function generateIslandRegistry(appDir: string): number {
  const mods = walk(appDir)
    .filter((f) => /\.(tsx|ts|jsx)$/.test(f) && !f.endsWith(ISLAND_REGISTRY_FILE))
    .map((f) => ({ f, src: readFileSync(f, "utf8") }))
    .filter(
      ({ src }) =>
        firstStatementIsDirective(src, "use client") &&
        /@junejs\/core\/poc-islands/.test(src) &&
        /\bisland\s*\(/.test(src),
    );

  const entries: string[] = [];
  for (const { f, src } of mods) {
    const rel = "./" + relative(appDir, f).replace(/\.(tsx|ts|jsx)$/, "");
    for (const name of exportNames(src)) {
      if (name === "default") continue; // islands are named exports
      entries.push(`  ${JSON.stringify(name)}: () => import(${JSON.stringify(rel)}),`);
    }
  }

  const body = entries.length ? entries.join("\n") + "\n" : "";
  const out =
    "// AUTO-GENERATED by June — do not edit. Lazy loaders for island() modules.\n" +
    "// Maps each island name to a lazy chunk loader; hydrateIslandsLazy consumes it.\n" +
    "export const ISLAND_LOADERS: Record<string, () => Promise<unknown>> = {\n" +
    body +
    "};\n";
  writeFileSync(join(appDir, ISLAND_REGISTRY_FILE), out);
  return entries.length;
}
