// Auto-generate the RSC client-reference wiring by scanning "use client" modules,
// so an app NEVER hand-writes registerClientReference / __webpack_require__ / the
// module maps. Two halves, both keyed by the SAME id (`<relPath>#<export>`):
//
//  1. SERVER graph (Flight render): a rolldown plugin replaces each "use client"
//     module's body with registerClientReference proxies — so `<Counter/>` in a
//     server component serializes as a client REFERENCE, not its impl.
//  2. SSR / BROWSER graphs (Flight consume): generated _rsc-client.gen.ts wires
//     __webpack_require__ → the real modules + the moduleMap, and _rsc-server.gen.ts
//     holds the render-side manifest (the webpackMap renderToReadableStream needs).
//
// Host-coupled (node:fs + rolldown types). Reuses the same "use client" scan as
// the island registry.
import { writeFileSync, readFileSync } from "node:fs";
import { join, relative } from "node:path";
import type { Plugin } from "rolldown";

import { walk, firstStatementIsDirective, exportNames } from "./island-registry";

export const RSC_SERVER_MANIFEST_FILE = "_rsc-server.gen.ts";
export const RSC_CLIENT_MANIFEST_FILE = "_rsc-client.gen.ts";

// Stable, per-export reference id shared by every graph: "<relPath no ext>#<name>".
function refId(appDir: string, absPath: string, name: string): string {
  const rel = relative(appDir, absPath).replace(/\.(tsx|ts|jsx)$/, "");
  return `${rel}#${name}`;
}

type ClientModule = { rel: string; abs: string; names: string[] };

function clientModules(appDir: string): ClientModule[] {
  return walk(appDir)
    .filter(
      (f) =>
        /\.(tsx|ts|jsx)$/.test(f) &&
        !f.endsWith(RSC_SERVER_MANIFEST_FILE) &&
        !f.endsWith(RSC_CLIENT_MANIFEST_FILE),
    )
    .map((abs) => ({ abs, src: readFileSync(abs, "utf8") }))
    .filter(({ src }) => firstStatementIsDirective(src, "use client"))
    .map(({ abs, src }) => ({
      abs,
      rel: "./" + relative(appDir, abs).replace(/\.(tsx|ts|jsx)$/, ""),
      names: exportNames(src).filter((n) => n !== "default"),
    }))
    .filter((m) => m.names.length > 0)
    .sort((a, b) => a.rel.localeCompare(b.rel)); // deterministic output
}

// SERVER-graph plugin: rewrite every "use client" module under appDir into
// registerClientReference proxies. Pass it ONLY to the server (react-server)
// bundle — the SSR/browser graphs load the real modules.
export function rscClientReferencesPlugin(appDir: string): Plugin {
  return {
    name: "june:rsc-client-references",
    transform(code, id) {
      if (!id.startsWith(appDir)) return null;
      if (!firstStatementIsDirective(code, "use client")) return null;
      const names = exportNames(code).filter((n) => n !== "default");
      let out = `import { registerClientReference } from "react-server-dom-webpack/server";\n`;
      for (const name of names) {
        const rid = refId(appDir, id, name);
        out += `export const ${name} = registerClientReference({}, ${JSON.stringify(rid)}, ${JSON.stringify(name)});\n`;
      }
      return { code: out, map: null };
    },
  };
}

// Write both manifest files. Returns the number of client modules wired.
export function generateRscManifests(appDir: string): number {
  const mods = clientModules(appDir);

  // Render-side manifest (flat by id) — the webpackMap for renderToReadableStream.
  let server = "// AUTO-GENERATED by June — do not edit. RSC render manifest.\n";
  server += "export const CLIENT_MANIFEST: Record<string, { id: string; chunks: string[]; name: string }> = {\n";
  for (const m of mods) {
    for (const name of m.names) {
      const rid = `${m.rel.slice(2)}#${name}`; // strip leading "./" → matches refId()
      server += `  ${JSON.stringify(rid)}: { id: ${JSON.stringify(rid)}, chunks: [], name: ${JSON.stringify(name)} },\n`;
    }
  }
  server += "};\n";
  writeFileSync(join(appDir, RSC_SERVER_MANIFEST_FILE), server);

  // Consumer side (SSR + browser): real modules + moduleMap, installs the webpack
  // shim. moduleMap is NESTED by export name (what client.edge resolves against).
  let client = "// AUTO-GENERATED by June — do not edit. RSC consumer manifest.\n";
  mods.forEach((m, i) => (client += `import * as m${i} from ${JSON.stringify(m.rel)};\n`));
  client += "\nconst CLIENT_MODULES: Record<string, unknown> = {\n";
  mods.forEach((m, i) => {
    for (const name of m.names) client += `  ${JSON.stringify(`${m.rel.slice(2)}#${name}`)}: m${i},\n`;
  });
  client += "};\n";
  client += "export const MODULE_MAP: Record<string, Record<string, { id: string; chunks: string[]; name: string }>> = {\n";
  for (const m of mods) {
    for (const name of m.names) {
      const rid = `${m.rel.slice(2)}#${name}`;
      client += `  ${JSON.stringify(rid)}: { ${JSON.stringify(name)}: { id: ${JSON.stringify(rid)}, chunks: [], name: ${JSON.stringify(name)} } },\n`;
    }
  }
  client += "};\n\n";
  client +=
    "const g = globalThis as Record<string, unknown>;\n" +
    "g.__webpack_require__ = (id: string) => CLIENT_MODULES[id];\n" +
    "g.__webpack_chunk_load__ = () => Promise.resolve();\n" +
    "export { CLIENT_MODULES };\n";
  writeFileSync(join(appDir, RSC_CLIENT_MANIFEST_FILE), client);

  return mods.length;
}
