// RSC build orchestrator — opt-in via app/_rsc.tsx (the root server component).
// Emits, under <outDir>/rsc/, everything a STANDARD worker needs to serve the RSC
// app (no native runtime): the server-graph bundle (app → Flight), the SSR worker
// (Flight → Document → HTML), and the generated client-reference manifests.
//
// Isolated from the main SSR pipeline: juneBuild only calls this when the opt-in
// file exists, so apps without it build exactly as before.
import { existsSync } from "node:fs";
import { mkdir, writeFile } from "node:fs/promises";
import { dirname, join } from "node:path";

import type { DocumentConfig } from "@junejs/core/document";

import { bundleServerGraph, bundleSsrGraph } from "./rsc-bundle";
import { generateRscManifests, RSC_CLIENT_MANIFEST_FILE } from "./rsc-manifest";

const RSC_ENTRY_BASENAMES = ["_rsc.tsx", "_rsc.jsx", "_rsc.ts"];

// The app's RSC root, if it opted in. Its presence enables the RSC build.
export function findRscEntry(appDir: string): string | undefined {
  for (const base of RSC_ENTRY_BASENAMES) {
    const f = join(appDir, base);
    if (existsSync(f)) return f;
  }
  return undefined;
}

// Resolve the runtime entries shipped by @junejs/server (this package's src).
function runtimeEntry(name: string): string {
  return join(dirname(new URL(import.meta.url).pathname), "rsc-runtime", name);
}

export type RscBuildResult = { worker: string; server: string } | null;

// Build the RSC app for `appRoot` into `<outDir>/rsc/`. Returns the emitted file
// names, or null if the app didn't opt in. `cwd` is where rolldown resolves
// node_modules (the app root, like the client/worker builds).
export async function buildRsc(
  appRoot: string,
  outDir: string,
  docConfig: DocumentConfig,
): Promise<RscBuildResult> {
  const appDir = join(appRoot, "app");
  const rscEntry = findRscEntry(appDir);
  if (!rscEntry) return null;

  // 1. Generate the client-reference manifests from the "use client" modules.
  generateRscManifests(appDir);

  // 2. Generate the doc-config module the worker imports (aliased june:rsc-config).
  const configFile = join(appDir, "_rsc-config.gen.ts");
  await writeFile(
    configFile,
    "// AUTO-GENERATED by June — do not edit. RSC document config.\n" +
      `export const DOC_CONFIG = ${JSON.stringify(docConfig)} as const;\n`,
  );

  const dest = join(outDir, "rsc");
  await mkdir(dest, { recursive: true });

  // 3. Server graph: app/_rsc.tsx → Flight (react-server condition + the
  //    client-references plugin auto-wires "use client" islands).
  const serverCode = await bundleServerGraph(
    runtimeEntry("flight-render.tsx"),
    appRoot,
    { "june:app": rscEntry },
    appDir,
  );
  await writeFile(join(dest, "server.js"), serverCode);

  // 4. SSR worker: Flight → <Document> → HTML (normal React). It loads server.js
  //    at runtime (separate react-server bundle) and resolves client references
  //    through the generated consumer manifest.
  const workerCode = await bundleSsrGraph(runtimeEntry("rsc-worker.tsx"), appRoot, {
    "june:rsc-client": join(appDir, RSC_CLIENT_MANIFEST_FILE),
    "june:rsc-config": configFile,
  });
  await writeFile(join(dest, "worker.js"), workerCode);

  return { worker: "rsc/worker.js", server: "rsc/server.js" };
}
