// RSC build orchestrator — PER-ROUTE, opt-in via the `page.rsc.tsx` convention.
// A route with a page.rsc.tsx is rendered through RSC (server graph → Flight →
// <Document> → HTML); every other route stays on the existing SSR/island pipeline.
// The two coexist behind a path dispatcher (createRscDispatch), so the SSR path is
// byte-unchanged when no RSC route exists.
//
// "use client" 分流 (the dual-semantics resolution): the SAME directive is read
// per ROUTE MODE. In an RSC route's server graph the client-references plugin turns
// "use client" into a true client reference (React-spec boundary); in an SSR/island
// route it stays an island scan marker. The two render paths are separate bundles,
// so one component file can serve both with no conflict.
import { existsSync } from "node:fs";
import { mkdir, writeFile } from "node:fs/promises";
import { dirname, join, relative } from "node:path";

import type { DocumentConfig } from "@junejs/core/document";

import { bundleServerGraph, bundleSsrGraph } from "./rsc-bundle";
import { generateRscManifests, RSC_CLIENT_MANIFEST_FILE } from "./rsc-manifest";
import { walk } from "./island-registry";

const RSC_ROUTES_FILE = "_rsc-routes.gen.tsx";
const RSC_PAGE_RE = /(?:^|\/)page\.rsc\.(tsx|jsx)$/;

export type RscRoute = { path: string; file: string };

// Scan app/** for page.rsc.tsx files → the RSC routes. Path is the route dir
// relative to app/ (route groups "(name)" stripped), "/" for the app root.
export function findRscRoutes(appDir: string): RscRoute[] {
  if (!existsSync(appDir)) return [];
  return walk(appDir)
    .filter((f) => RSC_PAGE_RE.test(f))
    .map((file) => {
      const dir = dirname(relative(appDir, file));
      const segs = dir === "." ? [] : dir.split("/").filter((s) => !/^\(.*\)$/.test(s));
      return { path: "/" + segs.join("/"), file };
    })
    .map((r) => ({ ...r, path: r.path === "/" ? "/" : r.path.replace(/\/$/, "") }))
    .sort((a, b) => a.path.localeCompare(b.path)); // deterministic
}

function runtimeEntry(name: string): string {
  return join(dirname(new URL(import.meta.url).pathname), "rsc-runtime", name);
}

export type RscBuildResult = { worker: string; server: string; paths: string[] } | null;

// Build all RSC routes for `appRoot` into `<outDir>/rsc/`. Returns the emitted
// files + the owned paths (for the dispatcher), or null if no RSC route exists.
export async function buildRsc(
  appRoot: string,
  outDir: string,
  docConfig: DocumentConfig,
): Promise<RscBuildResult> {
  const appDir = join(appRoot, "app");
  const routes = findRscRoutes(appDir);
  if (routes.length === 0) return null;

  // 1. Client-reference manifests from the "use client" modules.
  generateRscManifests(appDir);

  // 2. The route map the server graph renders against (path → view default export).
  let routesGen = "// AUTO-GENERATED by June — do not edit. RSC route map.\n";
  routesGen += 'import type React from "react";\n';
  routes.forEach((r, i) => {
    const rel = "./" + relative(appDir, r.file).replace(/\.(tsx|jsx)$/, "");
    routesGen += `import V${i} from ${JSON.stringify(rel)};\n`;
  });
  routesGen += 'export { CLIENT_MANIFEST as clientManifest } from "./_rsc-server.gen";\n';
  routesGen += "export const ROUTES: Record<string, React.ComponentType> = {\n";
  routes.forEach((r, i) => (routesGen += `  ${JSON.stringify(r.path)}: V${i},\n`));
  routesGen += "};\n";
  await writeFile(join(appDir, RSC_ROUTES_FILE), routesGen);

  // 3. The doc-config module the worker imports (aliased june:rsc-config).
  const configFile = join(appDir, "_rsc-config.gen.ts");
  await writeFile(
    configFile,
    "// AUTO-GENERATED by June — do not edit. RSC document config.\n" +
      `export const DOC_CONFIG = ${JSON.stringify(docConfig)} as const;\n`,
  );

  const dest = join(outDir, "rsc");
  await mkdir(dest, { recursive: true });

  // 4. Server graph: route views → Flight (react-server condition + the
  //    client-references plugin auto-wires "use client" islands).
  const serverCode = await bundleServerGraph(
    runtimeEntry("flight-render-routes.tsx"),
    appRoot,
    { "june:rsc-routes": join(appDir, RSC_ROUTES_FILE) },
    appDir,
  );
  await writeFile(join(dest, "server.js"), serverCode);

  // 5. SSR worker: Flight → <Document> → HTML (normal React), per request path.
  const workerCode = await bundleSsrGraph(runtimeEntry("rsc-worker.tsx"), appRoot, {
    "june:rsc-client": join(appDir, RSC_CLIENT_MANIFEST_FILE),
    "june:rsc-config": configFile,
  });
  await writeFile(join(dest, "worker.js"), workerCode);

  return { worker: "rsc/worker.js", server: "rsc/server.js", paths: routes.map((r) => r.path) };
}

type Fetcher = (request: Request) => Promise<Response>;

// The 分流: route RSC-owned paths to the RSC worker, everything else to the SSR
// pipeline. Exact-path match (RSC routes are explicit). This is what lets the two
// render models coexist behind one fetch handler.
export function createRscDispatch(
  ssrFetch: Fetcher,
  rscFetch: Fetcher,
  rscPaths: Iterable<string>,
): Fetcher {
  const owned = new Set(rscPaths);
  return (request: Request) => {
    const path = new URL(request.url).pathname;
    return owned.has(path) ? rscFetch(request) : ssrFetch(request);
  };
}
