// AUTO-GENERATED by June — do not edit. Lazy loaders for client:* islands.
// Maps each island name to a loader that resolves its component; hydrateIslands uses it.
export const ISLAND_LOADERS: Record<string, () => Promise<unknown>> = {
  "Counter": () => import("./Counter").then((m) => m.Counter),
  "Live": () => import("./Live").then((m) => m.Live),
};
