// A deployable Cloudflare Worker: a durable agent on the edge, one Durable
// Object per session — with the agent DEFINITION compiled from the agent/
// directory (agent/_agent.gen.ts, regenerated by `june gen`) instead of
// hand-written here. The worker keeps only what is genuinely the app's: the DO
// shell (model + env wiring) and the two routed surfaces.
//
//   wrangler dev     → http://localhost:8787   (offline: scripted model, no key)
//   wrangler deploy  → live                     (set ANTHROPIC_API_KEY for real Claude)
//
// Try it:
//   curl -sX POST localhost:8787/message -d '{"message":"order 3 widgets","session":"s1"}'

import { DurableObject } from "cloudflare:workers";
import { AgentDurableObject, durableAgentSurface, durableChannelSurface, type DurableObjectNamespace } from "@junejs/server/agent-durable";
import { anthropic } from "@junejs/core/agent-models";
import { assembleDurable } from "@junejs/core/agent-config";
import { replyStream, type Model, type ModelDelta, type Msg } from "@junejs/core/agent-runtime";

import agentModule from "./agent/_agent.gen";

type Env = {
  AGENT: DurableObjectNamespace;
  ANTHROPIC_API_KEY?: string;
  // Crisp secrets — present only in the worker env (never at module scope on
  // workerd), which is why agent/channels/crisp.ts is a `(env) => Channel` factory.
  CRISP_SIGNATURE_SECRET?: string;
  CRISP_IDENTIFIER?: string;
  CRISP_KEY?: string;
};

// Offline fallback so `wrangler dev` works with no API key — the Model seam is
// pluggable, so no MSW / HTTP interception is needed to run the whole loop
// deterministically. Swap in anthropic() the moment a key is present.
const scripted: Model = (msgs: Msg[]): AsyncIterable<ModelDelta> => {
  const placed = msgs.some((m) => m.role === "tool" && m.name === "create_order");
  if (!placed) return replyStream({ text: "Placing your order.", toolCalls: [{ id: "c1", name: "create_order", input: { item: "widget", qty: 3 } }] });
  return replyStream({ text: "Done — order placed.", toolCalls: [] });
};

// The compiled definition: adapted tools (+ read_skill when skills exist), the
// assembled system prompt, channel factories, source-keyed overlays — everything
// the agent/ directory declares, statically imported so it bundles for workerd.
const def = assembleDurable(agentModule);

// One DO = one session. The app supplies this thin shell; it delegates to
// @junejs/server's AgentDurableObject (which runs the durable loop over
// ctx.storage.sql). Real Claude when a key is set, else the offline model.
export class JuneAgentDO extends DurableObject<Env> {
  #agent = new AgentDurableObject(this.ctx, {
    ...def,
    model: this.env.ANTHROPIC_API_KEY
      ? anthropic({ model: agentModule.config.model ?? "claude-opus-4-8", apiKey: this.env.ANTHROPIC_API_KEY })
      : scripted,
    env: this.env, // channel factories resolve their secrets from the DO env
  });
  fetch(req: Request): Promise<Response> {
    return this.#agent.fetch(req);
  }
}

// The Worker routes two inbound edges to the per-session DO, both via June helpers —
// no hand-rolled webhook, no module-global signing-secret setter:
//   • POST /message            → durableAgentSurface (the chat endpoint)
//   • POST /channels/crisp     → durableChannelSurface (verify sig with env secret,
//                                derive the session, run the turn, reply back to Crisp
//                                on ctx.waitUntil). Everything else 404s.
export default {
  fetch(req: Request, env: Env, ctx: { waitUntil(p: Promise<unknown>): void }): Promise<Response> {
    const chat = durableAgentSurface(() => env.AGENT, { agentName: def.name, chatPath: "/message" });
    const channels = durableChannelSurface(() => env.AGENT, {
      agentName: def.name,
      channels: def.channels,
      env,
      waitUntil: ctx.waitUntil.bind(ctx),
    });
    return chat(req)
      .then((r) => r ?? channels(req))
      .then((r) => r ?? new Response('POST /message {"message","session?"}', { status: 404 }));
  },
};
