// AUTO-GENERATED by `june build` — edit content/**/*.md, not this file.
export type ContentEntry = { slug: string; data: Record<string, string | string[]>; body: string; original: string; html: string };
