// `june dev` watch supervisor — a restart IS the reload mechanism. The host's
// ESM module cache cannot be invalidated (re-importing an edited file is a
// cached no-op), so the only honest reload is a fresh process: the supervisor
// watches the app root and respawns the server child on change. Push-based
// HMR belongs to the native runtime track; this is the Bun/Node host's story.

import { spawn, type ChildProcess } from "node:child_process";
import { watch } from "node:fs";
import { sep } from "node:path";

const IGNORED_DIRS = new Set(["node_modules", ".git", "dist", ".june"]);

// Exported for tests. `app/_content.*` is generated by `june gen` — watching
// it would loop (content change → regen → _content event → regen …).
export function ignoredPath(file: string): boolean {
  const parts = file.split(sep);
  if (parts.some((p) => IGNORED_DIRS.has(p))) return true;
  return parts.length === 2 && parts[0] === "app" && /^_content\.[^/]+$/.test(parts[1]!);
}

export function superviseDev(root: string): undefined {
  let child: ChildProcess | undefined;
  let restarting = false;

  const start = () => {
    // Respawn this exact invocation (bin + argv) with the child marker set.
    child = spawn(process.execPath, process.argv.slice(1), {
      stdio: "inherit",
      env: { ...process.env, JUNE_DEV_CHILD: "1" },
    });
    child.on("exit", (code) => {
      if (restarting) return;
      // Died on its own (e.g. a broken june.config.ts). Stay alive: the next
      // save restarts it — exiting here would make the user re-run dev by hand.
      console.error(`[june] dev server exited (${code ?? "?"}) — waiting for changes`);
      child = undefined;
    });
  };

  const restart = async (file: string) => {
    if (restarting) return; // an edit mid-restart is picked up by the next save
    restarting = true;
    if (file.startsWith(`content${sep}`)) {
      // The frozen manifest must be fresh BEFORE the new server boots.
      try {
        const { generateContent } = await import("@junejs/server");
        await generateContent(root);
      } catch (err) {
        console.error("[june] content regen failed:", err);
      }
    }
    console.log(`[june] ${file} changed — restarting`);
    const c = child;
    if (!c) {
      // The child already died (crash state) — just bring a fresh one up.
      restarting = false;
      start();
      return;
    }
    c.once("exit", () => {
      restarting = false;
      start();
    });
    c.kill();
  };

  let pending: string | undefined;
  let timer: ReturnType<typeof setTimeout> | undefined;
  watch(root, { recursive: true }, (_event, file) => {
    if (!file || ignoredPath(file)) return;
    pending = file;
    clearTimeout(timer);
    timer = setTimeout(() => void restart(pending!), 80);
  });

  for (const sig of ["SIGINT", "SIGTERM"] as const) {
    process.on(sig, () => {
      child?.kill(sig);
      process.exit(0);
    });
  }

  start();
  return undefined;
}
