// AUTO-GENERATED by June — do not edit. RSC render manifest.
export const CLIENT_MANIFEST: Record<string, { id: string; chunks: string[]; name: string }> = {
  "Tabs#Tabs": { id: "Tabs#Tabs", chunks: [], name: "Tabs" },
};
