// AUTO-GENERATED by June — do not edit. RSC consumer manifest.
import * as m0 from "./Tabs";

const CLIENT_MODULES: Record<string, unknown> = {
  "Tabs#Tabs": m0,
};
export const MODULE_MAP: Record<string, Record<string, { id: string; chunks: string[]; name: string }>> = {
  "Tabs#Tabs": { "Tabs": { id: "Tabs#Tabs", chunks: [], name: "Tabs" } },
};

const g = globalThis as Record<string, unknown>;
g.__webpack_require__ = (id: string) => CLIENT_MODULES[id];
g.__webpack_chunk_load__ = () => Promise.resolve();
export { CLIENT_MODULES };
