import type { RouteContext, Loaded } from "@junejs/core/route";
// Frozen content (generated by `june build` from content/posts/*.md). Importing
// the FROZEN module keeps this route's worker graph free of node:fs — the
// content pipeline runs at build time, not in the worker (reminder #4).
import { post } from "../../_content";

export const loader = (ctx: RouteContext<{ slug: string }>) => ({
  post: ctx.params.slug ? post(ctx.params.slug) : null,
});

export default function Post({ post }: Loaded<typeof loader>) {
  return post ? (
    <main>
      <article dangerouslySetInnerHTML={{ __html: post.html }} />
    </main>
  ) : (
    <main>
      <h1>Post not found</h1>
    </main>
  );
}

// The .md projection is the AUTHORED source, verbatim — frozen at build, served
// byte-for-byte. Agents read exactly what the author wrote.
export const md = ({ post }: Loaded<typeof loader>) => post?.original ?? "# Post not found\n";

export const metadata = ({ post }: Loaded<typeof loader>) => ({
  title: (post?.data.title as string) ?? "Post",
  description: post?.data.description as string,
});
