import { route } from "junecore/route";
// Frozen content (generated by `june build` from content/posts/*.md). Importing
// the FROZEN module keeps this route's worker graph free of node:fs — the
// content pipeline runs at build time, not in the worker (reminder #4).
import { post } from "../../_content";

export default route({
  load: (ctx) => ({ post: ctx.params.slug ? post(ctx.params.slug) : null }),
  view: ({ post }) =>
    post ? (
      <main>
        <article dangerouslySetInnerHTML={{ __html: post.html }} />
      </main>
    ) : (
      <main>
        <h1>Post not found</h1>
      </main>
    ),
  // The .md projection is the AUTHORED source, verbatim — frozen at build,
  // served byte-for-byte. Agents read exactly what the author wrote.
  md: ({ post }) => post?.original ?? "# Post not found\n",
  metadata: ({ post }) => ({
    title: (post?.data.title as string) ?? "Post",
    description: post?.data.description as string,
  }),
});
