// BUILD-time codegen for messages (the @junejs/i18n/codegen entry — node:fs lives
// here, never in the runtime index). Reads `messages/<locale>.json` (ICU strings),
// compiles each to its AST, and emits a module that:
//   - registers the COMPILED catalogs (defineMessages) — the request bundle ships
//     ASTs + the evaluator, never the parser; and
//   - exports a TYPED `t` whose key AND params are derived from the ICU AST of the
//     default locale — the differentiator (`t("cart.items", { n: number })`).

import { readdirSync, readFileSync } from "node:fs";
import { join } from "node:path";

import { compileCatalog, deriveParams, type CompiledCatalog, type ParamType } from "./compile";

const TS_TYPE: Record<ParamType, string> = {
  string: "string",
  number: "number",
  Date: "Date",
  tag: "(chunks: ReactNode) => ReactNode",
};

/** Read + compile messages → compiled catalogs keyed by locale. Two layouts,
 *  mergeable: flat `messages/<locale>.json` (root keys) and namespaced
 *  `messages/<locale>/<ns>.json` (keys prefixed `<ns>.`). The runtime half of the
 *  codegen, exposed for tests. */
export function loadMessages(messagesDir: string): {
  catalogs: Record<string, CompiledCatalog>;
  raw: Record<string, Record<string, string>>;
  locales: string[];
} {
  const raw: Record<string, Record<string, string>> = {};
  const readJson = (path: string) => JSON.parse(readFileSync(path, "utf8")) as Record<string, string>;
  const merge = (locale: string, entries: Record<string, string>) =>
    Object.assign((raw[locale] ??= {}), entries);

  for (const ent of readdirSync(messagesDir, { withFileTypes: true })) {
    if (ent.isFile() && ent.name.endsWith(".json")) {
      merge(ent.name.replace(/\.json$/, ""), readJson(join(messagesDir, ent.name)));
    } else if (ent.isDirectory()) {
      const locale = ent.name;
      const sub = join(messagesDir, locale);
      for (const f of readdirSync(sub).filter((x) => x.endsWith(".json"))) {
        const ns = f.replace(/\.json$/, "");
        const prefixed: Record<string, string> = {};
        for (const [k, v] of Object.entries(readJson(join(sub, f)))) prefixed[`${ns}.${k}`] = v;
        merge(locale, prefixed);
      }
    }
  }

  const catalogs: Record<string, CompiledCatalog> = {};
  for (const [locale, entries] of Object.entries(raw)) catalogs[locale] = compileCatalog(entries);
  return { catalogs, raw, locales: Object.keys(catalogs) };
}

// The TS shape of one message's params (from its AST), or Record<string, never>.
function paramsType(catalog: CompiledCatalog, key: string): string {
  const params = deriveParams(catalog[key]!);
  const names = Object.keys(params);
  // Record<never, never> (not Record<string, never>!) so `keyof` is `never` — the
  // signal that lets the typed `t` take NO second arg for a param-less message.
  if (names.length === 0) return "Record<never, never>";
  return `{ ${names.map((n) => `${JSON.stringify(n)}: ${TS_TYPE[params[n]!]}`).join("; ")} }`;
}

/** Generate the frozen `_messages.ts` module text from `messages/`. The default
 *  locale is the type source of truth (its keys define `Messages`). */
export function generateMessagesModule(
  messagesDir: string,
  opts: { defaultLocale: string },
): { code: string; locales: string[] } {
  const { catalogs, locales } = loadMessages(messagesDir);
  const defaultCatalog = catalogs[opts.defaultLocale] ?? {};
  const entries = Object.keys(defaultCatalog)
    .sort()
    .map((key) => `  ${JSON.stringify(key)}: ${paramsType(defaultCatalog, key)};`)
    .join("\n");

  const code =
    "// AUTO-GENERATED by `june gen` — edit messages/*.json, not this file.\n" +
    'import { defineMessages, t as rawT, type CompiledCatalog } from "@junejs/i18n";\n' +
    'import type { ReactNode } from "react";\n\n' +
    `const CATALOGS: Record<string, CompiledCatalog> = ${JSON.stringify(catalogs)};\n\n` +
    `defineMessages(CATALOGS, { defaultLocale: ${JSON.stringify(opts.defaultLocale)} });\n\n` +
    "// The message keys + their params, derived from the default locale's ICU ASTs.\n" +
    `export type Messages = {\n${entries}\n};\n\n` +
    "// A key with a <tag> param has a function param → it must go through t.rich.\n" +
    "type HasTag<P> = true extends\n" +
    "  { [K in keyof P]: P[K] extends (...a: never[]) => unknown ? true : never }[keyof P]\n" +
    "  ? true : false;\n" +
    "type PlainKey = { [K in keyof Messages]: HasTag<Messages[K]> extends true ? never : K }[keyof Messages];\n\n" +
    "// Typed translate: key AND params are checked against messages/*.json. A no-\n" +
    "// param message takes no second arg; a wrong/missing param or unknown key is a\n" +
    "// compile error. t.rich renders <tag>s to ReactNode (tag keys require it).\n" +
    "export const t = rawT as unknown as {\n" +
    "  <K extends PlainKey>(\n" +
    "    key: K,\n" +
    "    ...args: keyof Messages[K] extends never ? [] : [params: Messages[K]]\n" +
    "  ): string;\n" +
    "  rich: <K extends keyof Messages>(\n" +
    "    key: K,\n" +
    "    ...args: keyof Messages[K] extends never ? [] : [params: Messages[K]]\n" +
    "  ) => ReactNode;\n" +
    "};\n";
  return { code, locales };
}
