// AUTO-GENERATED by June — do not edit. Lazy loaders for client:* islands.
// Maps each island name to a loader that resolves its component; hydrateIslands uses it.
export const ISLAND_LOADERS: Record<string, () => Promise<unknown>> = {
  "HeroViewer": () => import("./HeroViewer").then((m) => m.HeroViewer),
  "InstallCmd": () => import("./InstallCmd").then((m) => m.InstallCmd),
  "ThemeToggle": () => import("./ThemeToggle").then((m) => m.ThemeToggle),
  "ViewAs": () => import("./ViewAs").then((m) => m.ViewAs),
};
