// AUTO-GENERATED by June — do not edit. Lazy loaders for island() modules.
// Maps each island name to a lazy chunk loader; hydrateIslandsLazy consumes it.
export const ISLAND_LOADERS: Record<string, () => Promise<unknown>> = {
  "HeroViewer": () => import("./HeroViewer"),
  "InstallCmd": () => import("./InstallCmd"),
  "ViewAs": () => import("./ViewAs"),
  "ThemeToggle": () => import("./ThemeToggle"),
};
