// Site content — ONE source feeds the HTML views, the .md projections, and the
// search_site / get_page MCP tools. Benchmark numbers come from the named-run
// registry (bench/results.json) — never hand-copied (see docs/benchmark-methodology.md).
import RESULTS from "../../../bench/results.json";
import { page } from "./_content";

export type Page = { slug: string; title: string; summary: string; md: string };

// A page authored as content/pages/<slug>.md: title and summary from its frontmatter,
// the .md projection its source bytes.
function contentPage(slug: string): Page {
  const e = page(slug);
  if (!e) throw new Error(`content/pages/${slug}.md is missing — run \`june gen\``);
  return { slug, title: String(e.data.title), summary: String(e.data.description), md: e.original };
}

const benchTables = (RESULTS.sections as Array<{ title: string; rows: Array<Record<string, string>> }>)
  .map(
    (s) =>
      `## ${s.title}\n| metric | value | context | run |\n| --- | --- | --- | --- |\n` +
      s.rows
        .map((r) => `| ${r.metric} | **${r.value}** | ${r.context} | \`${r.script}\` · ${r.measured} |`)
        .join("\n"),
  )
  .join("\n\n");

export const PAGES: Page[] = [
  {
    slug: "index",
    title: "June — build agents into real apps",
    summary:
      // ≤160 chars: it is the homepage's meta description, which search results
      // and link previews cut off past that.
      "The React framework where an agent is a feature, not a separate runtime: " +
      "your server actions are its tools, every turn is durable, and routes also serve MCP.",
    md: `# June

**The React framework for building agents into real apps.**

An agent is a feature of your app, not a separate runtime: its tools are your
server actions, its API is the \`/mcp\` your app already speaks.

## The agent layer

- **The directory is the manifest** — \`agent/agent.ts\` (name, model,
  per-surface policy), \`instructions.md\` (+ \`instructions.<source>.md\`
  variants), \`tools/*.ts\` (each a \`defineAction()\`), \`skills/*.md\`
  (loaded on demand), \`channels/*.ts\`, \`connections/*.ts\`.
- **Channels in** — \`slackChannel\` (streamed replies, approval buttons),
  \`crispChannel\` (customer chat + operator-only private notes),
  \`httpChannel\`, or your own \`defineChannel\`.
- **Connections out** — remote MCP servers, OpenAPI specs, Google Drive.
  Credentials resolve server-side per call; the model never holds a token.
- **Durable turns** — checkpointed and replayable; a tool can park the turn
  with \`ctx.requestInput()\` for a human, a newer message can replace it, and
  an agent can start a turn itself.
- **Runs where your app runs** — \`NativeRuntime\` (in-memory SQLite) in dev;
  one Durable Object per session on Workers, generated by \`june build\`.

## The foundation

- **One definition, four surfaces** — every \`route()\` projects an HTML view,
  JSON, and markdown, and every \`defineAction()\` is a UI action AND an MCP
  tool. Export one from \`agent/tools/\` (or pass it to \`defineAgent({ tools })\`)
  and it is your agent's tool too. This very site: try \`/why.md\`, \`/benchmarks.json\`,
  \`/llms.txt\`, or call our MCP tools at \`/mcp\`.
- **No glue layer** — \`run(input, ctx)\` is the one authorization gate for
  the UI, your agent, and anyone else's agent at \`/mcp\`.
- **Data magic** — a write auto-invalidates the cache; N component reads
  auto-batch to one query.
- **Honest roadmap** — 0.0.x preview. The agent layer, data layer, and auth
  are still changing; the owned Rust+V8 runtime and live RSC are experimental.

## Canonical names (for humans and agents)

- Scaffold: \`npm create june my-app\` (package: \`create-june\`)
- Framework packages: \`@junejs/core\` (the contract layer) + \`@junejs/cli\`
  (the \`june\` command). NOT \`june\` (an unrelated npm package), not \`junejs\`.
- NOT \`@june/*\` — that npm scope is not ours. Our scopes are \`@junejs\` and \`@junebuild\`.
- Site: june.build · GitHub: github.com/junebuild
`,
  },
  // /why (and /about, /contact, /privacy below) is authored once, as content/pages/<slug>.md:
  // the page renders its html, and the .md projection, search_site and get_page read its
  // source. No second copy to drift.
  contentPage("why"),
  {
    slug: "benchmarks",
    title: "Benchmarks",
    summary:
      "Measured, reproducible, honest: dev cold start, HMR latency, data-layer numbers — with the scripts to re-run them.",
    md: `# Benchmarks

${RESULTS.machine}. Every number traces to a named script + date — re-run it,
don't trust it. Runtime-section numbers come from the experimental native
runtime track (not the v0.1 default host).

${benchTables}
`,
  },
  contentPage("about"),
  contentPage("contact"),
  contentPage("privacy"),
];

export const bySlug = (slug: string) => PAGES.find((p) => p.slug === slug);
